### ISSUE TITLE
Fill in  Research Information page

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#117]
# Goal
Exchange the placeholder information in the Research Information page for the actual study details

Research Name: Vocalized Daily Diary
Research Duration: Nov 2023
Researcher Name: Dr. Deanna Kaplan

⚠️ Let's make sure this also applies to the Research Summary page in the Home page

**Comment by yago1994** [comment]
@JayceKongg added the sign in info here

**Comment by yago1994** [comment]
@Wiza-Munthali given that this info appears in both places, it might be good to store it as a variable that can be reused in multiple areas (i.e. Contact Us email pre-filled with this info, etc)

**Comment by Wiza-Munthali** [comment]
@yago1994 Way ahead of you 🙃, The information is being stored in resources and please let me know when all the information is available

**Comment by yago1994** [comment]
@Wiza-Munthali love it!
Here is the blurb for the Research Description (taken out of the consent form):
The purpose of this study is to test a smartphone app for daily diary research called Fabla, to find out how well it works and how easy it is for people to use. Fabla is a new app developed by the Georgia CTSA AppHatchery. The study will also assess how people’s spoken reports about their day compare to their written reports about their day. Participation in this study takes about two weeks to complete. 

During the daily diary study, you will be asked to respond to some questions every day before you go to bed for two weeks. The daily diary will take about 10 minutes to complete each time, and it asks you to share about:
- how your day was, 
- your interactions with other people that day, 
- and whether anything stressful happened. 

If you have questions about the study procedures, appointments, research-related injuries or bad reactions, or other questions or concerns about the research or your part in it, contact the Principal Investigator at 404-727-1360.

--

Also a couple other things:
- The app is going to be named: Fabla. So we should change it in the splash page.
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/d2a393b2-4944-4f44-a9fa-7d113aef2ffe)
- The ghost will be: Fabio. Just need to change that in the speech bubble. Maybe needs animation @JayceKongg ?
- Changing the logo to: 
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/a3f36d91-4588-4022-9510-b05e42e1f057)
- Change Verification Code to Participant ID to be consistent with what users expect




I believe after this we should be good!

**Comment by JayceKongg** [comment]
Yes, we need to update the speech bubble that contains the ghost's name. (When the ghost first appears)

<img width="600" alt="Screenshot 2023-10-13 at 11 26 41" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/15e98c35-05da-4c40-9854-bb3e4a178b64">

**Comment by JayceKongg** [comment]
### The logo can be found here:
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4811%3A66575&mode=design&t=KSaSfsyyT3oTSK3T-1](url)

### Attach a high-resolution logo (SVG):
![White](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/bada01f6-264a-43e7-872c-51f910e65f43)

**Comment by Wiza-Munthali** [comment]
@yago1994 This looks good guys, Quick one though. We still need an email for the support(the login page)

**Comment by yago1994** [comment]
> @yago1994 This looks good guys, Quick one though. We still need an email for the support(the login page)

Email is going to be info@apphatchery.org
