### ISSUE TITLE
Bug: Tips for you banner did not appear on first diary start

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#120]
# Goal
Display the 'Tips for you' banner when the user starts a diary
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/9a40b81f-1dd6-42b3-a004-f5aeb287bf02)

## Considerations
- If user selects 'Don't show me again' this should not display the banner again (save in SharedPreferences)
- 'Got it!' button and Exit button both dismiss the banner
- Banner should include the opaque backdrop

**Comment by JayceKongg** [comment]
### Update the illustration and text in the banner.

[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=5072%3A10792&mode=design&t=KSaSfsyyT3oTSK3T-1
](url)

<img width="600" alt="Screenshot 2023-10-13 at 11 53 34" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/7b92fca7-ea8b-4047-8af4-2bfd6c263531">
