### ISSUE TITLE
Onboarding Update - Reminder time

### ISSUE THREAD

**Issue by JayceKongg** [AppHatchery/Fabla-Front-end#122]
# Goal
1. Clarify the difference between "Reminder Time" and "Diary Time"
2. Add a quick way to delete/edit reminder time
3. Simplify wheel picker - 5 mins increments to reduce spacing
4. Optimize headings (reminder setting & enable notification) for smooth meaning

**Comment by JayceKongg** [comment]
# Reminder Setting Page
### Figma link: 
**Active Time page**
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=5070%3A9181&mode=design&t=iq61BqeAHNnQaqxB-1
](url)
**wheel picker**
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=5070%3A34235&mode=design&t=iq61BqeAHNnQaqxB-1
](url)


### Change the title to "When would you like to receive reminders?"
<img width="600" alt="Screenshot 2023-10-13 at 11 08 57" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/13296231-e2a9-492a-a6fa-a690d718953c">

### Change the text in the speech bubble to "Feel free to add or edit the reminders below."
(Changes in speech bubbles will be realized in animations.)
<img width="600" alt="Screenshot 2023-10-12 at 21 39 52" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/f7e74fb1-f10c-42eb-9710-dfe75c6dd99c">

### Add a "delete" icon in the reminder time card, change the "edit" icon color to blue
<img width="600" alt="Screenshot 2023-10-12 at 21 41 31" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/74089d49-0f07-49a4-8b16-a69ec4dc646e">

### Set the minimum interval for the time setting to 5 minutes, and remove "delete" in the bottom sheet
<img width="600" alt="Screenshot 2023-10-12 at 21 42 06" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/f8fd1e84-66c2-498b-90cb-4a252cbcc700">

**Comment by JayceKongg** [comment]
# Enable Notification Page

### Figma Link:
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=5070%3A34143&mode=design&t=iq61BqeAHNnQaqxB-1](url)

### Change the title to "Turn on notifications for timely reminders!"
<img width="600" alt="Screenshot 2023-10-12 at 21 48 10" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/2c7115ea-7b64-4640-ab03-0d4a6d37e122">

### Change the speech bubble text to "All reminders will only be related to your diaries."
(Changes in speech bubbles will be realized in animations.)
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/b7305da8-2ace-4dc5-8ab3-6f213ad7eec8)

**Comment by yago1994** [comment]
@JayceKongg Small typo, it should be"When would you like to receive reminder**s**"

Also let's not say "Get notified only for your set reminders." This is just FALSE, we are going to notify the users way more, i.e. if they forget, to continue the diary, to submit, etc,. We should be consistent in our messaging with what the app will actually do.

**Comment by JayceKongg** [comment]
@yago1994 Thank you for correcting me. Corrected them
1. When would you like to receive reminders
2. The reminders will only be related to your diaries.
