### ISSUE TITLE
Data Upload to S3

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#13]
# Goal
Upload an audio file from Flutter to AWS S3 Bucket

## Considerations
- File conversion to base64 for including in payload
- ⚠️ We are going with an API implementation for now due to issues with Flutter SDK
- No encryption needed at this stage
- AWS Bucket and Lambda function should be under AppHatchery account so everybody is able to access it for testing
- Code uploaded to Lambda for handling the audio file and passing it to S3 should be included in a separate repository Audio-Diaries-Backend

## For Merge into Main
- Upload code should trigger in the 'Success' page @Wiza-Munthali will add a section in the codebase for that function to go in

**Comment by yago1994** [comment]
@kennedylinzie can you:
1. Create a new repo inside the AppHatchery organization called Audio-Diaries-Backend 
2. Add an issue that describes the creation of the lambda function
3. Push a PR and merge it for the lambda function code

**Comment by kennedylinzie** [comment]
Will do

**Comment by Wiza-Munthali** [comment]
When issue #11 is merged into main you'll find an upload.dart file in lib/core/network/ that's where you'll add the uploading function and in the lib/screens/diary/domain/repository/ you'll find a file called summary_repository.dart in that file you need to scroll to the last function and you'll find a TODO where you will replace it with the upload function.
