### ISSUE TITLE
Survey Flow Update - Tips before start.

### ISSUE THREAD

**Issue by JayceKongg** [AppHatchery/Fabla-Front-end#131]
# Goal
Remind users to find a quiet place before starting.

**Comment by JayceKongg** [comment]
## Tips pop-up:
It is only shown to the user once a day. Once the user clicks "Don't show me again", it will be removed for the entire duration of the study.

### Figma link:
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4633%3A23525&mode=design&t=foMyKwAoeMhkb5j9-1](url)

### Screenshot:
<img width="600" alt="Screenshot 2023-10-13 at 02 13 39" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/b0cc4075-e7a3-45f0-b739-74cb8e623135">

**Comment by yago1994** [comment]
Covered in #132
