### ISSUE TITLE
Onboarding Update - Study Information

### ISSUE THREAD

**Issue by JayceKongg** [AppHatchery/Fabla-Front-end#145]
# Goal
Update the study information page to provide the research overview and requirements to users.
1. Participants need to submit by 4 AM the following day
2. Participants can't the submit diary if they miss one
3. Participants need to achieve a 65% response rate.

![image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/bc945680-0b84-4009-9eb7-15f5e918004f)

**Comment by JayceKongg** [comment]
We will be providing the study information in two places, one is on the "Study Information" page when the user taps the "View Study Details" button. The second is on the home screen when the user clicks the button in the top right corner.

### Figma link
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=5145%3A48327&mode=design&t=GzLEB7kNpUn3FSWi-1](url)

### Screenshot
<img width="300" alt="Screenshot 2023-10-17 at 21 33 52" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/75f25167-04d4-46a5-b9d5-118a7f327ad1">


### Content
I've included the content here, please check and let me know if any errors or misinformation exist. @yago1994 

**Study Overview**
The purpose of this study is to test a smartphone app for daily diary research called VoiceDiary, to find out how well it works and how easy it is for people to use. 

During the research, you will need to answer the questions using VoiceDiary, which will ask you to speak your responses out loud to record them. The daily diary will take about 10 minutes to complete each time, and it will ask you to share about how your day was, your interactions with other people that day, and whether anything stressful happened. 

**Time and Completion Rates**
- The deadline for submitting a diary is 4 AM the following day.
- If you miss a diary submission, you will not be able to submit it unless it is due to technical issues.
- To earn extra credit from your instructor, you will need to respond to at least 65% of the daily diaries.

**Comment by JayceKongg** [comment]
## Update:
I found the study information was updated on the app, which is great. So let's simplify the work.

1. Add the title "Study Information" and a "x" button to dismiss the page
2. Add the subtitles "Study Overview" and "Time and Completion Rates" 
3. Add the row above the institution to display the study name

<img width="300" alt="Screenshot 2023-10-18 at 11 27 16" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/bfbfa25f-4f13-4efb-84d0-0759cc1b0bf8">

**Comment by yago1994** [comment]
Looks good @JayceKongg , although if the stuff that's important is the Times and Completion Rates I'd move that higher up in the view. Users will need to scroll to get to it.

**Comment by JayceKongg** [comment]
Move the Times and Completion Rates higher up in the view.

<img width="300" alt="Screenshot 2023-10-18 at 12 11 07" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/34ebfcb8-a308-4cb7-8421-b55337cc385e">
