### ISSUE TITLE
Unify text on applications

### ISSUE THREAD

**Issue by JayceKongg** [AppHatchery/Fabla-Front-end#146]
# Goal
Avoid misunderstanding of information

## Tasks
1. Change the title "Today's Tasks" to "Today's Diary" in the Home Page
2. Change the title "Research Information" to "Study Information" in the Onboarding
3. Change the subtitle "Research Name", "Research Duration" and "View Research Details" to "Study Name", "Study Duration" and "View Study Details" in the Onboarding

**Comment by JayceKongg** [comment]
# Home page 
Change the title "Today's Tasks" to "Today's Diary"
<img width="300" alt="Screenshot 2023-10-17 at 21 27 00" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/4880b300-2978-4743-8edd-30c1b74d87de">

# Onboarding - Study Information page
Change the title "Research Information" to "Study Information"
Change the subtitle "Research Name", "Research Duration" and "View Research Details" to "Study Name", "Study Duration" and "View Study Details"
<img width="300" alt="Screenshot 2023-10-17 at 21 29 06" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/085e9133-265f-4801-afbb-68d4ed4a8585">

**Comment by Wiza-Munthali** [comment]
Study Information page already done in #151

**Comment by Naomi-Nyama** [comment]
Already done in #151
