### ISSUE TITLE
Text Update

### ISSUE THREAD

**Issue by JayceKongg** [AppHatchery/Fabla-Front-end#153]
# Goal
Fix textual errors and clarifications.

**Comment by JayceKongg** [comment]
# Welcome Screen
Subtitle -> You are now checked into our study. Thank you so much for joining! 🎉

Covered in #144 

<img width="300" alt="Screenshot 2023-10-19 at 16 15 12" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/b04def17-0a3b-4d3d-8037-b0cf2bef2fdd">

**Comment by JayceKongg** [comment]
# Name screen
Title -> Enter a nickname for the study.
Input field -> Nickname

Covered in #159  
<img width="300" alt="Screenshot 2023-10-19 at 16 16 32" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/38ac4f79-c257-4c7d-89d2-9750bb2b55bd">

**Comment by JayceKongg** [comment]
# Notification Page & Mic Access Page - Button Text

"Continue" - "Allow" (Optional, not necessary if it takes too much time)

<img width="300" alt="Screenshot 2023-10-19 at 16 32 26" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/38d21a14-b774-42de-9267-9c49ed08f7bd">

<img width="300" alt="Screenshot 2023-10-19 at 16 33 04" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/0a815a2c-cab1-4148-9c54-77971a70b522">

**Comment by yago1994** [comment]
# Replace Study Name placeholder with Vocalized Daily Diary

Covered in #159 

<img width="263" alt="image" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/75c10bc5-d247-4efd-a60e-7c8ba30b059e">

**Comment by yago1994** [comment]
# Replace Continue button to Allow for Notifications and Microphone permission
Make it obvious to the User that they can click the button on the page to make the request

@JayceKongg should we change the Ghost message on the microphone page then?

**Comment by yago1994** [comment]
@JayceKongg include here the changes about Privacy, for the pop up about quiet place

**Comment by JayceKongg** [comment]
I've combined these two pieces of information to pop up before we start recording. Since we want to cover more information, I made it a dialog in the center of the screen. But if you prefer to use a button sheet, I have a design for that as well. @yago1994 

**Figma link:**
[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=5247%3A8690&mode=design&t=TAmaFzrixDwk15hV-1](url)

![Tips](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/7cb384d6-de27-4221-8f7e-2137cb5944b1)

![Tips](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/cb032a31-fce0-416b-a561-b7238d0546ca)

**Comment by JayceKongg** [comment]
> # Replace Continue button to Allow for Notifications and Microphone permission
> Make it obvious to the User that they can click the button on the page to make the request
> 
> @JayceKongg should we change the Ghost message on the microphone page then?

Attach the animation below: (Because we need to replace animations for the mic test screens, I updated the body shape of the ghost meantime.)

**MicAccess&Test**
[micAccess.zip](https://github.com/AppHatchery/Audio-Diaries-Flutter/files/13079439/micAccess.zip)

**WelcomePage**
[onboarding_welcome 2.riv.zip](https://github.com/AppHatchery/Audio-Diaries-Flutter/files/13079451/onboarding_welcome.2.riv.zip)

**Comment by yago1994** [comment]
@hopemadziakapita can you try this animation for onboarding welcome?
