### ISSUE TITLE
Animation - Animation location and speech bubble text update

### ISSUE THREAD

**Issue by JayceKongg** [AppHatchery/Fabla-Front-end#155]
# Goal
1. Clarify the meaning (i.e., how many diaries in total users need to take...) 

# Note
The text issue is minor, we can skip it if we don't have enough time.

# Screens
1. Calendar screen in onboarding. (2 animations are involved: calendar and reminder)
2. Recording component. (2 animations are involved: pause and ongoing)

# Bug
1. Ghost location at standard screen size (iPhone 13) - The problem occurs on the boarding, name entry page. As shown in the image below

<img width="300" alt="Screenshot 2023-10-19 at 16 52 34" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/4d8452f6-fcab-47d8-9c7e-595016cbbc49">

**Comment by JayceKongg** [comment]
### Animations:
[RecordingAnimation.zip](https://github.com/AppHatchery/Audio-Diaries-Flutter/files/13047738/RecordingAnimation.zip)
[OnboardingAnamtion.zip](https://github.com/AppHatchery/Audio-Diaries-Flutter/files/13047739/OnboardingAnamtion.zip)

### What the text looks like after updating

Onboarding:

<img width="300" alt="Screenshot 2023-10-19 at 16 58 56" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/ba2dfce9-2614-4268-b3f5-1b1a2752bd0b">

Recording:

<img width="300" alt="Screenshot 2023-10-19 at 16 58 36" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/770bcae1-d574-4360-9aad-ee07c999095d">

**Comment by yago1994** [comment]
@JayceKongg let's make sure we cover this, the bit from Deanna on the speech bubble saying "What's on your mind" seems pretty important.

Is it ready to pass to dev?

**Comment by JayceKongg** [comment]
> RecordingAnimation

Yes, it's covered in my comment above. I attached the animation again here. 

[RecordingAnimation2.zip](https://github.com/AppHatchery/Audio-Diaries-Flutter/files/13167001/RecordingAnimation2.zip)

**Comment by yago1994** [comment]
Sorry @Wiza-Munthali adding you here last minute, the comment about the speech bubble asking a different question was pretty important as it was brought up by the client, we'll need to include that for the study-ready version. Let us know if you have any questions

**Comment by Wiza-Munthali** [comment]
🙂 No problem
