### ISSUE TITLE
Button Update - Record my response

### ISSUE THREAD

**Issue by JayceKongg** [AppHatchery/Fabla-Front-end#161]
# Goal
Clarify the "record" function for users. Usability tests showed that users were confused upon arriving to this screen given they had been answering slider and multiple choice questions.

**Comment by JayceKongg** [comment]
Add a microphone icon to the "Record my response" button. The spacing between the icon and the text is 8pt.

<img width="300" alt="Screenshot 2023-10-23 at 13 38 34" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/a239e44a-80e9-4876-804a-9b8f6aa52609">

Attach the SVG icon here (24ptx24pt):

![keyboard_voice](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/033634d4-85b2-4b36-8ce7-2fdaaea6d956)

**Comment by JayceKongg** [comment]
Add the same microphone icon to the "Add a new response" button. The spacing between the icon and the text is 8pt.

<img width="300" alt="Screenshot 2023-10-26 at 11 59 03" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/f01013a7-e5be-45df-8a6e-90e7c22bb3c6">

**Comment by yago1994** [comment]
That is there on the latest build @JayceKongg 
![IMG_2771](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/4583ce6c-bb72-4edb-913d-57ba15282be6)
