### ISSUE TITLE
When the user clicks Allow microphone or Notifications the button label should change to Continue

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#167]
# Bug
The button text says 'Allow' for those two screens, which matches the instructions expected for the users on what to do. However, after the user clicks the button the label should change to 'Continue'.

For the notifications permission -> user is allowed to NOT permit notifications so they should be able to click Continue
For the microphone permission -> 
- If users click 'Don't allow' the button should remain in the Allow state and direct the users to open settings if they click the button again
- If users click 'Allow' the button label should change to 'Continue'

**Comment by yago1994** [comment]
@Wiza-Munthali can I ask you to take a look at this and gauge whether it could be done fast (< 1 hr)? If not we'll leave for next round

**Comment by Wiza-Munthali** [comment]
All add it to the audio issue
