### ISSUE TITLE
Submit question responses temporarily in files

### ISSUE THREAD

**Issue by Ikay-real** [AppHatchery/Fabla-Front-end#176]
# Malfunctioning data upload using GraphQL
## Issue: 
The upload function to GraphQL of participants responses started presenting issues last Friday Oct 27th where data would not upload at all at random times. Issue hasn’t been fully identified.
## Contingency plan: 
a) Uploading a json file to S3 containing all the participants responses for the given diary

## Tasks: 
- Upload a json file containing the questions and answers from the participant for the given day at the time of the upload of audio to s3

**Comment by yago1994** [comment]
Closed in #178
