### ISSUE TITLE
Incorporate written response to audio question

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#184]
# Goal
Incorporate the option of adding a text entry instead of audio

## Considerations
- Users can only add text or audio but not both
- Consider the storage of the data if the user selects text instead of audio

## Design for reference
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/a6229fb9-260e-4cbd-8c71-5a2f022407bf)
https://www.figma.com/file/Gevs9eDsnIzVaq1qfvfSeE/M2---Winship-Study?type=design&node-id=18%3A12828&mode=design&t=iqLx1BwmAhojNR0a-1

**Comment by JayceKongg** [comment]
https://www.figma.com/file/Gevs9eDsnIzVaq1qfvfSeE/M2---Winship-Study?type=design&node-id=18%3A12828&mode=dev

<img width="100%" alt="Screenshot 2024-02-12 at 11 06 16" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/d8535004-43b6-4a01-a06c-e115e8ba8f54">
