### ISSUE TITLE
Audio question - UI

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#185]
# Goal
Based on feedback from the validation study we want to make the audio input more standardized to avoid inconsistencies in behavior of the previous screen

## Considerations
- Build the UI elements
- Ignore the "Try a hint" functionality (future scope)
- Attach the functionality of redo and save buttons to new buttons
- Audio recording does NOT activate by default when the modal appears
- Modal cannot be dismissed when the user is recording

## Reference
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/09c74813-c627-48a3-a953-0b040cc5f0dc)
https://www.figma.com/file/Gevs9eDsnIzVaq1qfvfSeE/M2---Winship-Study?type=design&node-id=18%3A12828&mode=design&t=iqLx1BwmAhojNR0a-1

**Comment by JayceKongg** [comment]
https://www.figma.com/file/Gevs9eDsnIzVaq1qfvfSeE/M2---Winship-Study?type=design&node-id=18%3A9942&mode=dev

<img width="100%" alt="Screenshot 2024-02-12 at 11 12 26" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/2791076b-410d-473c-b64e-bfb870304a20">

**Comment by Wiza-Munthali** [comment]
@JayceKongg what is the behavior when the recording surpasses the 5 minutes mark?

**Comment by JayceKongg** [comment]
> @JayceKongg what is the behavior when the recording surpasses the 5 minutes mark?

I think display the time is fine, such as 5:10 / 5:00 - but for now I don't know the time mark for the winship study.
