### ISSUE TITLE
Explore carousel type survey flow

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#187]
# Goal
To make the interaction across questions more fluid we want to evaluate whether using a carousel-type display for the questions. 

Goal is determining the feasibility of this design

## Considerations
- Only the questions change, the progress bar and the next - back arrows are static
- User can only move through questions using the buttons at the bottom, not by dragging
- Movement from one question to the next should be an animation rather than screen change
- Ignore the time picker for this scope

## Questions
- Do the questions all need to be loaded up front? What is the time cost of this? Limitations?
- What is the added complexity of managing different question types within one controller? Specifically audio questions with the modals?

## Reference

https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/ff867fb5-a7bb-43ec-bd60-583c7f78abd2

**Comment by JayceKongg** [comment]
https://www.figma.com/file/Gevs9eDsnIzVaq1qfvfSeE/M2---Winship-Study?type=design&node-id=13%3A8176&mode=dev

<img width="100%" alt="Screenshot 2024-02-22 at 15 10 14" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/33e8c527-c7f5-4570-b9ae-8214e38d2531">

**Comment by Naomi-Nyama** [comment]
@yago1994 Can you please add the screen recording showing the lag here
