### ISSUE TITLE
Survey submission page - UI

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#188]
# Goal
Increase gamification elements in the app to encourage users to make more submissions as well as displaying remaining days in the study

## Considerations
- Circle filling is animated after the user arrives to this page
- Animation should start from previous end point (i.e. if user completed 25% of the diaries of the day, the next submission goes from 25% -> 50%)
- Circle filling should include dynamic functionality to account for filling in halves, quarters, etc,.
- Calendar display below goes from Monday - Sunday
- Calendar circles need to be dynamic like big wheel above
- Text below the calendar will also be dynamic
- (out of scope) hiding the days were the user did not make a submission

## Reference
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/49c84516-c480-4a1c-9b22-ec791e4e3197)

State for missed entries

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/45b17ff5-d879-41d6-a258-38887738c3af)

**Comment by JayceKongg** [comment]
https://www.figma.com/file/Gevs9eDsnIzVaq1qfvfSeE/M2---Winship-Study?type=design&node-id=45%3A42797&mode=dev

<img width="100%" alt="Screenshot 2024-02-12 at 10 06 17" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/b224fabb-beff-48d7-9ae2-ad6649a87141">
