### ISSUE TITLE
Homepage - Card

### ISSUE THREAD

**Issue by JayceKongg** [AppHatchery/Fabla-Front-end#191]
### Overview
- Cards will be displayed on the Home, History and Study Calendar pages. For users to view and select tasks as well as track their progress.
- The entire card is clickable and initiates the opening behavior.
<img width="500" alt="Screenshot 2024-02-22 at 12 41 49" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/b7cf6ba6-dfa2-4003-a76b-4a9a686d7d3c">

### What will be included in cards
- Tags (Entry Type)
- Survey Title
- Est. Complete Time
- CTA (Get Started / Continue)
<img width="776" alt="Screenshot 2024-02-22 at 12 45 31" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/e78d2d34-a71e-41f2-a3f5-36c565e2ef9c">

### Margins
The left stroke color is 4pt wide. 
<img width="776" alt="Screenshot 2024-02-22 at 12 46 45" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/c623b7d9-56a4-4dd0-9755-18a475c18b94">

**Comment by JayceKongg** [comment]
### 3 Card States 

<img width="1150" alt="Screenshot 2024-02-22 at 12 47 36" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/4919248d-a759-491d-b8d4-79d823b2f371">

**Comment by yago1994** [comment]
@JayceKongg do you want the card color to be purple? Shouldn't it match the color of the circle that the ghost is completing?

**Comment by JayceKongg** [comment]
> @JayceKongg do you want the card color to be purple? Shouldn't it match the color of the circle that the ghost is completing?

Let's go with blue. I will update it.
