### ISSUE TITLE
Test build and archive with XCode 15

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#197]
# Goal
Verify that project and app can be built and archived with XCode 15 with all dependencies (Pendo included).

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/c5aac982-3e90-47ae-8d16-d9f0889e7e3f)

⚠  THIS MAY IMPACT OTHER FLUTTER PROJECTS LIKE TONSILLECTOMY

**Comment by MorganGreenleaf-Emory** [comment]
Able to build to simulator 17.4 using Xcode 15.3.  Able to archive.
v1.4 ok for test flight? @yago1994

**Comment by yago1994** [comment]
Works, closing
