### ISSUE TITLE
Bug on recording screen after user clicks redo

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#202]
# Bug
If user is recording and presses the redo button the timer acts strange. See video below. This seems to be an issue with multiple timers acting at once and adding up together.

Minor bugs:
- Show me again button does not work either, keeps showing the user. I suggest we remove this option from the view until we decide
- When user presses redo, the previous waveform is still present, I'd suggest to clear the view and start anew to emphasize to the user that the recording is being redone
- Color contrast on Cancel button does not pass the accessibility test, we should adjust that design and color the background or the text color. This feels like a design system change @JayceKongg 

https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/0f69ad5c-16e8-4ad6-ac1f-02866826bfe9

**Comment by JayceKongg** [comment]
@yago1994 Yes, good point. We could use darker blue on the recording modal and buttons. It is a design system change (include buttons) - I will update the design file.

![Record](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/1bb2c823-2c5d-4e8c-913d-ed364c2ca9a9)
