### ISSUE TITLE
Visual bug on onboarding nickname input is blocked

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#209]
# Goal
Fix the visual bug where the nickname participants input gets covered by the keyboard appearing.

## Considerations
- Regular font size at 100% still displays this behavior
- Whole view should slide up to display the text field

## Design Reference
@JayceKongg drop the visuals and description here please
## Issue Reference
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/91bc8aa9-849f-4434-a21e-c3529ea13894)

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/c991e06f-b6ec-4d11-97c5-e51ed8619beb)

**Comment by yago1994** [comment]
Reopening this issue
- Initial keyboard appearance looks correct

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/6bd7258a-a924-4774-923a-bbb4eb9a862b)

- BUG: however user can scroll down underneath the field and a lot of white space is visible
- INTENDED BEHAVIOR: content below the input field should maintain the same height as originally before the keyboard appears

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/e4e3c3a3-940b-4963-a338-4f51141bf719)

**Comment by yago1994** [comment]
@hopemadziakapita idea, similarly to the login page, could we have the Continue button sit right below the input field (at approximately the same distance as in the login page) ONLY when the keyboard is displayed?

**Comment by Wiza-Munthali** [comment]
Handled in PR #232
