### ISSUE TITLE
Bug on audio recording screen sizing

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#212]
# Bug
The audio question text gets covered by the recording blue area when the content on the page overflows half the page. 

## Intended behavior
All the page should be scrollable if not all content is visible

## Reference
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/0c62e63c-bc8c-4ed9-a6b9-06cf178e26dc)

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/860c40d8-47e1-4b6d-996b-c7dca0f6c338)

**Comment by yago1994** [comment]
@JayceKongg can you add the video here for reference?

**Comment by JayceKongg** [comment]
> @JayceKongg can you add the video here for reference?

https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/97614683-82ad-4bb2-9485-d9b97064a089
