### ISSUE TITLE
Onboarding Finish Page

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#22]
# Goal
Close the onboarding and bring the user to the home page

![Image](https://user-images.githubusercontent.com/16402216/264094482-832da56e-5914-4160-8532-b385824bd14d.png)

## Considerations
- @JayceKongg can you find a confetti animation we could use?

**Comment by Wiza-Munthali** [comment]
https://lottiefiles.com/search?q=confettie

you can check out some royalty free animations here if it helps

**Comment by yago1994** [comment]
Look great to me!
