### ISSUE TITLE
End page functionality

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#224]
## Tasks
- Movement of the progress circle should match number of total entered submissions (total submissions entered / total submissions needed for daily goal)
- Movement of circle should start from previous number of submissions (total submissions - 1 / daily goal)
- Circles in the calendar DO NOT need to be animated
- Connect days displayed on the calendar to days active in the study active_days variable
- Days where the user did not submit any diary should be hidden from the view
- Change language at the bottom of weekly view to match the # entries left for the day (daily goal - total submissions)

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/39c236bb-b389-433d-a47f-8be05905901b)

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/12721eec-c763-4878-a1b8-949d7ec7dca4)

**Comment by yago1994** [comment]
Edit: no need to hide the missing days from the view

Hide Saturday and Sunday to be consistent with submission expectations with the home page

**Comment by yago1994** [comment]
@Wiza-Munthali can you give this task to Hope and Maxwell?

> Edit: no need to hide the missing days from the view
> 
> Hide Saturday and Sunday to be consistent with submission expectations with the home page

**Comment by Wiza-Munthali** [comment]
@yago1994 my issue will need to be closed first so, if they can wait that's okay
