### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#24]
# Goal
Include UI elements to the Settings page to reduce user-error on notification and microphone permissions

## Tasks
- Remove the toggle switches and exchange for a card with a button to route the user to the General Settings page
- When the user enables a permission, the UI should not allow them to disable it from within the app
- When notification permissions are disabled, the old reminders remain on the Setting page, but they are disabled.
- Users should be allow to edit/add/delete reminders from the app
![image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/42c88ea8-2591-4755-8b09-6e545c041ed2)
<img width="305" alt="image" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/ca057b41-16dd-4d35-a3f5-8fa49a0cb5c8">
<img width="323" alt="image" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/601b27d5-8b23-4004-9149-072eb3d4af35">
<img width="244" alt="image" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/941ca2a5-ded7-403a-95a6-b81251c2b361">

##

# Previous Goal
Allow the user a central place where they can modify the app's settings

## Considerations
- User should see the status of their notification access (allowed or not allowed)
- User should be able to route to the General Settings to turn on notifications
- User should be able to erase all self-reported data from the app (diaries & name), study dates should remain
- Add Emory Logo to page (follow Emory's spacing requirements i.e. one M padding around logo)
- Page should include the version number of the app (i.e. 1.1)
- Page should include a Send us Feedback button that launches the Native Mail app and has a prefilled email to support@apphatchery.org
- Page should include a Problems with the Research? button that launches the Native Mail app and sends a message to clinical partner email TBD
- Examples of support email
![Image](https://user-images.githubusercontent.com/16402216/264096812-36e2f6ea-352e-44e2-8edf-329e82bd8e5c.jpeg)

**Comment by yago1994** [comment]
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/5d50a46e-32db-4372-91f7-7d94f56d0a4a)

**Comment by JayceKongg** [comment]
Design Update: See mock-ups in Figma:

[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4129%3A4708&mode=design&t=aDOM2uYY4peL2UKx-1](url)

<img width="1080" alt="Screenshot 2023-09-02 at 01 10 36" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/f130db88-dfea-4665-9b6a-106b7b1ba0be">

**Comment by yago1994** [comment]
@JayceKongg what to do if user toggles off any of the permissions

**Comment by yago1994** [comment]
@Naomi-Nyama from our chat this morning:
- Change name of 'Reminders' to 'Notifications'
- Remove the reminders UI from the Settings page (it should just be the toggle switch)
- Behavior of going to the general Settings page is correct

@JayceKongg for us to think about (will make a low priority ticket for this):
- Differentiating between Reminders vs Notifications
- Clarity of system behavior (app vs system settings)
- Edge cases of turning off reminders and re-adding them

**Comment by JayceKongg** [comment]
Reminders: Settings within our App. Any actions performed on Reminders will not affect Notifications.
Notifications: System settings (if the user allows us to send Reminders). Also, actions on Notifications won't influence Reminders.

⬇️ Figma:
https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4356%3A49587&mode=design&t=CyAJE760psGMWz6p-1

Ideal: (Toggle button controls Reminders almost exclusively, except for first-time users who have not yet enabled Notifications)

- If a user disables notifications at the system level
- (The first time) we will send a popup window to the user allowing them to enable notifications directly.
- If the user taps "Not Allowed", we will provide another button "Open Settings" to direct the user to the system settings page.
- If the user has enabled "Notifications" but disabled "Reminders", we will save the reminder time for the user (disable the time setting) and activate the reminder for them the next time they click the toggle button.

![Ideal Notification   Reminder Request](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/87f70855-151c-4078-a40a-1dad373b82fc)

Alternative: We rename "Reminders" to "Notifications". This way, every time the user clicks the toggle button, we send it to the System Settings page.

![Alternative Notification Request](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/ed6ca5d3-16fc-4304-991c-07e22bbc65ef)

**Comment by yago1994** [comment]
@JayceKongg keep in mind people won't be "first time" users arriving at the Settings page because they have to go through onboarding, so the first case where the microphone is requested won't happen.

I like the disabled state for the Reminders when they are turned off

Question: 
- If a user has disabled the reminders are we allowed to send them notifications if they miss a diary?

**Comment by JayceKongg** [comment]
@yago1994 Should I update the settings page here? If the user has disabled notifications in the system, we will display the "Disabled reminder time selector (displays the time set by the user during onboarding)" under the "Reminders" section in the Settings page.

To clarify the logic, the two cards directing the user to the system settings will only appear if the user disables the microphone and notifications at the system level.
<img width="535" alt="Screenshot 2023-10-05 at 16 01 48" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/1d127f98-2f6e-4e29-b15a-d555987ce413">

Figma Link: https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4672%3A65706&mode=design&t=Qv6UmVodHfh9YowZ-1

<img width="1254" alt="Screenshot 2023-10-05 at 15 52 51" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/8fb18cbe-79a7-48d7-9797-7a44894a15e7">

**Comment by yago1994** [comment]
This looks good @JayceKongg I will update the ticket

**Comment by JayceKongg** [comment]
Hi @Naomi-Nyama, Can you check the resolution of the Emory logo on the settings page? I know you are working on the settings page, but it looks a little blurry right now. You can find the Logo in Yago's comment above.
<img width="500" alt="Screenshot 2023-10-11 at 01 00 46" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/69641c7c-03af-4025-a030-0d79a541de0e">

One more small update, sorry for the repeated changes, could you temporarily remove "Terms of Use" and "Provide Feedback" and use the layout shown in the screenshot below?
<img width="500" alt="Screenshot 2023-10-11 at 00 59 36" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/55d7f25b-9971-43b9-9a1b-b94778e6759e">

**Comment by yago1994** [comment]
@JayceKongg @Naomi-Nyama adding to your small change above:
Change app name to Audio Diaries Version 1.0
