### ISSUE TITLE
Onboarding Study dates

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#25]
# Goal
To provide the user with a general study schedule, what days and how long the study is going to be

## Considerations
- Study length will be 5 days TOTAL (including the day the app was opened for the first time)
- @JayceKongg design needs to account for 'Today' in terms of appearance of the day bubble
- Language of the speech bubble is TBD (include lorem ipsum placeholder for now)

![Image](https://user-images.githubusercontent.com/16402216/264097598-4216314d-d16d-4cd5-af06-ecab9662d1c0.png)

**Comment by JayceKongg** [comment]
Design Update: Update the calendar to include "today" as a day in the study period.

[https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4159%3A51895&mode=design&t=aDOM2uYY4peL2UKx-1
](url)

![ActiveDays](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/2cefa769-dd2c-40d9-9eb7-e7f8914fbcb5)
