### ISSUE TITLE
Add data upload functionality for user responses when submitting diary

### ISSUE THREAD

**Issue by Ikay-real** [AppHatchery/Fabla-Front-end#258]
Goal: Add upload data upload functionality for user responses.

**1. Uploading user responses to dynamo db**
    Use URL provided by the API gateway
**2. Uploading files to S3** 
    Use pre-signed URL which is generated by the backend code base of the API gateway

**Comment by yago1994** [comment]
Format for Audio files
StudyCode_DateTime.mp3
