### ISSUE TITLE
Add animations

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#260]
# Goal 
Add animations to celebrate users progress

## Tasks
- Make sure you are able to control the state machine on a random page
- Integrate animation file in home page & end page
- Call specific animation states depending on given conditions, start simple

## Animation Placement
- First Arrival, displayed in:
  - Finishing onboarding and opening the home screen
  - Closing the app completely and re-opening it (i.e. initial build of home_screen.dart)
- Searching_1 & Searching_2 randomly displayed (50% chance of each appearing) in:
  - Home page on a new day and there are no submissions
- Searching_3, displayed in:
  - Home page when there are > 1 submissions completed
- Cheering, displayed in:
  - Submission page after making any submission <  daily goal
- Celebration, displayed in:
  - Submission page after making a submission == daily goal
- Surprise + Approve, displayed in:
  - Submission page after making any submission > daily goal 
- Blinking + Blowing the horn, displayed in:
  - Home page when user has achieved the daily goal 
- Achieving the goal, displayed in:
  - Home page when user has achieved the weekly goal
- Beyond the goal , displayed in:
  - Home page when the user has gone beyond the weekly goal 

State Machine
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/ed3406f6-5b0a-4f44-91a4-3994ba2546f0)

[ghost animations.zip](https://github.com/AppHatchery/Audio-Diaries-Flutter/files/15264766/ghost.animations.zip)

**Comment by Wiza-Munthali** [comment]
> ## Animation Placement
> 
>     * First Arrival, displayed in:
>       
>       * Finishing onboarding and opening the home screen
>       * Closing the app completely and re-opening it (i.e. initial build of home_screen.dart)
> 
>     * Searching_1 & Searching_2 randomly displayed (50% chance of each appearing) in:
>       
>       * Home page on a new day and there are no submissions

@yago1994 may you please explain how the searching 1 and 2 are supposed to be displayed? If a user hasn't submitted any should the app transition from the first arrival to the searching state after some minutes or after the user returning to the app?

**Comment by yago1994** [comment]
Good question, and I'll throw the question back to you, how hard would it be to make the home page dynamic where after 30 seconds of idleness the animation state would change?

Alternatively, if it's too custom, we can display the searches in this scenario:
- the user leaves the app (without terminating it) and comes back 

So far arrival animation looks 👌

**Comment by yago1994** [comment]
Adding animations to free response question (audio, listening animations and written, reading animation)

**Comment by Wiza-Munthali** [comment]
### Extra Goal:
Adding in scroll behavior for the recording modal: If the recording modal isn't already at the bottom then the app should automatically scroll to the bottom when the user presses record to show the other recording controls
