### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#261]
# Goal
Add notification reminders to participants to encourage participation

### **Daily Reminder (scheduled by participants)**

🐰 All scheduled on the onboarding when the user sets the reminders.

🔫 Fired daily (M - F). Could be multiple notifications

⚠️ The first daily reminder (if more than one) gets removed if the user **begins** the diary → Reason for this is to avoid overburdening the user with general notifications if they start the diary on their own accord

⏲️  1x notification scheduled

- Title: "Record your conversations with staff!"
- Content: "Hey there! Have you had a conversation with staff today? Take a couple minutes to record your thoughts"

⏲️ ⏲️  > 1x notifications scheduled

- Title: "Reminder to record your conversations with staff!"
- Content: "Hey there! Just another check-in. Remember it takes just a minute, don’t forget to record your thoughts after talking to the staff"

### **Daily Goal Reminder (scheduled by the system)**

🐰 Scheduled during the first entry completed

🔫 Fired daily (M - F) under the following conditions

⚠️ Removed when the user **accomplishes the daily goal**

- **IF YES** daily reminder (set by the user)
    - If ANY reminder is after 3p → schedule +1 hrs in the future (until 19:00)
    - If ALL reminders are before 3p → schedule at 3p

⏲️ Notification

- Title: "You still have time to accomplish your goal!"

### **Continue Diary (scheduled by the system)**

🐰 Scheduled when the user **has begun a diary and the app is sent to the background (quits or phone closes) or when the user exits the flow**

⚠️ Removed when the user **completes the diary (arrives at the submission screen)**

🔫 Fired daily under the following conditions

- 1x Scheduled at Date() + 30 mins (until 19:00)

⏲️ +30 mins Notification

- Title: "Time to Continue Your Entry!"
- Content: "Don't forget to continue where you left off. We appreciate your input!"

### **Submit Diary (scheduled by the system)**

🐰 Scheduled when the user **arrives at the summary screen and the app is sent to the background (expected to be very rare) or when the user exits the review page**

⚠️ Removed when the user **uploads the diary**

🔫 Fired daily under the following conditions

- 1x Scheduled at Date() + 10 mins (until 19:00)

⏲️ Notification

- Title: "Your Entry Is Ready for Submission!”
- Content: "You've completed your entry. Fantastic! Just one more step: hit 'Submit' to share your valuable thoughts.”

**Comment by Naomi-Nyama** [comment]
@yago1994 can you add the description for this issue
