### ISSUE TITLE
Adjust Widget and Text Sizing for All Font and Screen Sizes

### ISSUE THREAD

**Issue by Naomi-Nyama** [AppHatchery/Fabla-Front-end#267]
Problem:
When using larger font sizes, the text and widgets in the application overflow, especially on the home page.
This problem is particularly noticeable on devices with smaller screens or when accessibility settings are adjusted for larger text.

Desired Outcome:
The application should dynamically adjust widget and text sizes to ensure that content is properly displayed across all font sizes and screen dimensions.

Steps to Reproduce:
1. Open the application on a device with a smaller screen 
2. Increase the system font size
3. Observe how text and widgets overflow 

=> Go through the entire app to make sure this issue doesn't exist on other pages.

⚠️ In the current main branch, the overflowing problem for the weekly goal pop-up is already being fixed in #207

**Comment by Naomi-Nyama** [comment]
@MaxwellKJr @hopemadziakapita

**Comment by MaxwellKJr** [comment]
If possible, could you provide a screenshot of the exact places on the home page? I have increased the font and display sizing on my phone but can't seem to reproduce all the overflow errors and my smallest emulator keeps freezing on the Home page. Screenshots of just the Home page will do.

**Comment by Naomi-Nyama** [comment]
![fabla-homepage](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/72823209/20d193d4-f2b8-4a9c-8593-9d25e13342ba)
![history](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/72823209/61427ff4-14fb-424a-9803-9302788de980)




I used the pixel 4(not emulator)

**Comment by hopemadziakapita** [comment]
![Screenshot 2024-05-16 123520](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/48337899/5e650b63-e212-4a78-9ae4-36c551d989e2)
![Screenshot 2024-05-16 112818](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/48337899/b4ed2eea-ab99-437b-ad9e-a2a702fdb09f)


I have worked on these two, find changes in the PR

**Comment by hopemadziakapita** [comment]
![resaerch](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/48337899/a4880da4-7e41-4d10-b98c-501fda50e82f)
@MaxwellKJr
