### ISSUE TITLE
Delete Old Recordings

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#27]
# Goal
Users should be able to delete old recordings that have already been submitted

## Considerations
- Data is only deleted from the diary entry but the diary metadata should persist

![Image](https://user-images.githubusercontent.com/16402216/264099337-11298bf7-1aab-4ee6-88f8-1917397b270c.png)

**Comment by Wiza-Munthali** [comment]
The functionality was already there, what was left was adding the pop up before performing the action. I'll add this in the #70 PR
