### ISSUE TITLE
Progress Indicator in the upload page

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#30]
## Goal
Display loading state to the user

Here are videos and links to the error and the success animations (update a little bit).
[https://www.figma.com/proto/OYey6QzMgX6sQ60prPcewf/Animations?page-id=10%3A2113&type=design&node-id=10-2128&viewport=-1094%2C-67%2C1.41&t=xnnG9x4kzETUAPCK-1&scaling=scale-down&starting-point-node-id=10%3A2128&show-proto-sidebar=1&mode=design](url)

https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/30a9e482-9f85-4afb-a95f-272d7a7b0f21
https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/e502ca7d-2b1a-4049-8cf6-351e1775fe6f

## Questions
- Path 1: Diary is done, app uploads automatically
  - [Question] App should try to upload the diary on the home screen?
  - All unsubmitted diaries have a tag 'Unsubmitted (defined in #111 )', that informs the user the diary hasn't been sent yet
- ✅  Path 2: User keeps ability to upload 
  - All unsubmitted diaries stay in the history page with the 'Submit' button, users can tap the button and go to the summary screen to submit the diary
  - The submission period never closes

Which path is simpler for development?

##

# Previous Goal
Because data upload takes a few seconds we should be displaying some loading state to the user.

## Considerations
- Simplest form of this will be a loading activity indicator
- More complex behavior could include a loop animation

**Comment by JayceKongg** [comment]
Figma file:

[https://www.figma.com/proto/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?page-id=4627%3A18592&type=design&node-id=4645-59863&viewport=1377%2C-7534%2C0.48&t=HovGZnS30ahzCJKh-1&scaling=scale-down&starting-point-node-id=4645%3A44500&show-proto-sidebar=1&mode=design](url)

Video:
https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/77b0581a-c8d9-4be8-a06a-6749da56eda7

**Comment by yago1994** [comment]
@JayceKongg tagging you to add error states to the loading screen

**Comment by JayceKongg** [comment]
About the error state animation, I would like to know:

1. What backup solutions can we offer our users if an error occurs
2. When does the error occur? Does it happen immediately after the user clicks 'submit my response', or after we have processed their response (several seconds)?

Here are videos and links to the error and the success animations (update a little bit).
[https://www.figma.com/proto/OYey6QzMgX6sQ60prPcewf/Animations?page-id=10%3A2113&type=design&node-id=10-2128&viewport=-1094%2C-67%2C1.41&t=xnnG9x4kzETUAPCK-1&scaling=scale-down&starting-point-node-id=10%3A2128&show-proto-sidebar=1&mode=design](url)

https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/30a9e482-9f85-4afb-a95f-272d7a7b0f21
https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/e502ca7d-2b1a-4049-8cf6-351e1775fe6f

**Comment by yago1994** [comment]
@JayceKongg can you upload here the icon for the error state? The static one

**Comment by JayceKongg** [comment]
Here is the SVG version of the error icon. 
![Spinner-Round-30](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/4cce4467-77c1-4213-ab33-8bb11c5abdd5)


And here's the Figma link [https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4935%3A25879&mode=design&t=setJ4Bj7uJSEBCVZ-1](url)

<img width="763" alt="Screenshot 2023-10-05 at 15 20 13" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/b3b2a286-ed65-4a01-b17f-3beec4596e0c">

**Comment by Wiza-Munthali** [comment]
@JayceKongg are you using Rive to make the animations? is there a way to access the Rive project, we need to export the animations as assets.

**Comment by JayceKongg** [comment]
> @JayceKongg are you using Rive to make the animations? is there a way to access the Rive project, we need to export the animations as assets.

Hi @Wiza-Munthali. Yes, I am using Rive to make animations. You can refer to #112.  I will update the link to the Rive project later there.
