### ISSUE TITLE
Bug on Study progress page

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#301]
# Bug
There may be a tentative bug on submitting diaries and displaying them in the home page. 

⚠️ Potentially related to manually changing phone dates

## Issues
- Home page does not display the due diary
- History page displays Yesterday when it should be Today with the correct date
- Progress page upon diary submission looks incorrect
 
## Steps to reproduce
- Submit a diary (on Tuesday)
- Change the date on the phone to the following Monday
- Go back to the app
- (Home page should be blank)
- Close the app and re-open it
- Go to History page (Diary date should be incorrectly marked as Yesterday)
- Submit the diary
- Progress screen should display wrong dates like below

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/72330f09-5891-4f5e-bc91-893724640b6b)

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/6d2660e3-9e31-4a70-8c4f-b85d4feea76b)

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/df6311d0-7a29-4898-8fa3-405d7f9aaea5)

Stake trace from XCode
`flutter: File content is {"participant":"1001","start_study_date":"1969-12-31-19-00-00","next_study_date":"1969-12-31-19-00-00","recent_submit_date":null,"diaries":{"day1":null,"day2":null,"day3":null,"day4":null,"day5":null,"day6":null}}`

**Comment by Wiza-Munthali** [comment]
@yago1994 I tested on the iPhone in Blantyre and Atlanta timezones but it is working just fine
