### ISSUE TITLE
Modify Calendar page to include incentive structure

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#337]
# Goal
Modify the current calendar page to include the incentive structure

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/47687eb1-8778-4f26-bcfe-5c9626a7d1a9)

**Comment by yago1994** [comment]
@crlund2024 added a quick mock up here to begin modifications to the incentive page, feel free to edit the ticket if you have an updated design. A few considerations:
- Given a multi-tier study with different phases (i.e. weeks where the diary submissions are different) how do we display the incentive structure to the user so they know what incentive is available without overwhelming them with too much information
- How to display the way to get the bonus incentives in a way that's clear
- How to display to the user what they can still achieve (i.e. progress tracking of incentive/diaries) and be transparent about where they are and what's attainable money-wise

**Comment by Wiza-Munthali** [comment]
@yago1994 is the currency going to be universally USD or is it an option that the researchers will pick out?

**Comment by Wiza-Munthali** [comment]
![image](https://github.com/user-attachments/assets/435c3b0b-36e3-4a7f-bd04-ede0a5d6a25f)

Updating the ticket to document the changes
