### ISSUE TITLE
Modify onboarding calendar page to include start_dates of the study

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#338]
# Goal
Modify the onboarding calendar page to reflect the days where diaries are starting 

## Considerations
- Use Start_date as the marker for selecting the day of the week
- Since this is an overview type of screen and not a progress tracking, we will not be considering the implications of only showing when to start and not when the diaries are due (i.e. 4am limitations, week long diaries, etc)

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/b4a094ea-6a2a-4dbb-9f12-ff88cac46399)

**Comment by yago1994** [comment]
@Wiza-Munthali added a ticket for tracking our conversation

**Comment by Wiza-Munthali** [comment]
> [@Wiza-Munthali](https://github.com/Wiza-Munthali) added a ticket for tracking our conversation

Thanks for saving me the trouble
