### ISSUE TITLE
Study description

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#347]
Add the text describing the study for participants to see when they onboard in the app.

[Figma Link](https://www.figma.com/design/zDk3k6dkxpBl9Eg4C4cfCy/M3---Experiments?node-id=8-3047&t=D1C8j06WLjbg30f5-1)

Images:
![Image](https://github.com/user-attachments/assets/a114e683-aa3e-4195-a59c-00e265c7fe95)
![Image](https://github.com/user-attachments/assets/3b6796d4-8e3e-4a7c-b618-9daa128673e0)

**Comment by crlund2024** [comment]
@yago1994 Does this look good to you?

**Comment by yago1994** [comment]
@crlund2024 can you edit the ticket to reflect the style we are going with as discussed this morning? Add the see more with the bullet points

**Comment by crlund2024** [comment]
@yago1994 Updated!

**Comment by yago1994** [comment]
@crlund2024 good, can you follow the styling from the Validation Study to increase legibility? 
<img width="436" alt="image" src="https://github.com/user-attachments/assets/9c7f92d2-c850-4a11-a45a-b2ba45fc1214">

**Comment by crlund2024** [comment]
@yago1994 Fixed!
