### ISSUE TITLE
Set up Firebase app Distribution

### ISSUE THREAD

**Issue by Naomi-Nyama** [AppHatchery/Fabla-Front-end#348]

**Comment by Naomi-Nyama** [comment]
@yago1994  I managed to get the issue with xcode fixed last night and now the only thing remaining is te team part to build for the archive.  This is what I am getting when I try to use my team:

![Image](https://github.com/user-attachments/assets/3f48d506-1200-4983-9f36-ccf666304aa5)

**Comment by yago1994** [comment]
@Naomi-Nyama let's push this back to do and focus on the other open items for the study, I can manage the archiving and distribution

**Comment by yago1994** [comment]
@Naomi-Nyama I think that issue with XCode has caught up to me! I can't archive or build the project anymore, I think it might have something to do with this 'check' commit where a bunch of project structure changes came in, mostly flutter fire related

![Image](https://github.com/user-attachments/assets/17f1a424-b90f-4586-9867-1a6e7a19873f)

Are you able to build the project if you pull from the user-engagement-test branch directly?

**Comment by Naomi-Nyama** [comment]
> [@Naomi-Nyama](https://github.com/Naomi-Nyama) I think that issue with XCode has caught up to me! I can't archive or build the project anymore, I think it might have something to do with this 'check' commit where a bunch of project structure changes came in, mostly flutter fire related
> 
> ![Image](https://github.com/user-attachments/assets/17f1a424-b90f-4586-9867-1a6e7a19873f)
> 
> Are you able to build the project if you pull from the user-engagement-test branch directly?

@yago1994 I managed to pull and build from the user-engagement-branch directly and it worked on my end 
We can go over it during today's meeting

**Comment by yago1994** [comment]
We can close this for now since no need for Firebase
