### ISSUE TITLE
Field Test Voice Diary Questions

### ISSUE THREAD

**Issue by crlund2024** [AppHatchery/Fabla-Front-end#352]
Considerations
- Shown on days 1-6 and days 8-13

Add text for field text voice diary questions

[Figma Link](https://www.figma.com/design/zDk3k6dkxpBl9Eg4C4cfCy/M3---Experiments?node-id=3112-6636&t=jEHEDTDcW4V08isc-1)

Images:
![Image](https://github.com/user-attachments/assets/909d55e0-0851-4178-b6ed-ed5851fc4f4e)

**Comment by crlund2024** [comment]
@yago1994

**Comment by crlund2024** [comment]
Link to confetti animation: [Link](https://drive.google.com/file/d/1vBAbwf-eebDhsp8754h9Jp3CQY9LBLgL/view?usp=sharing)

Can't upload .RIV files directly to comments, but I think anyone should be able to grab it from there.

@yago1994

**Comment by yago1994** [comment]
Please put this in notion inside the M2 field engagement files

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yago1994** [comment]
Added here @Naomi-Nyama https://www.notion.so/apphatchery/User-Engagement-Fabla-Field-Test-Protocol-924d6d3d9acd455c93056adab0014e25
