### ISSUE TITLE
Midpoint and Final Voice Diary Questions

### ISSUE THREAD

**Issue by crlund2024** [AppHatchery/Fabla-Front-end#354]
Considerations
- Shown on the 7th and 14th days of the study

[Figma Link](https://www.figma.com/design/zDk3k6dkxpBl9Eg4C4cfCy/M3---Experiments?node-id=8-3047&t=jEHEDTDcW4V08isc-1)

Images:
![Image](https://github.com/user-attachments/assets/6b643557-ee15-4275-a7e9-a572ceb95592)

**Comment by crlund2024** [comment]
@yago1994

**Comment by yago1994** [comment]
@crlund2024 can we combine this with the Midpoint and Final Questions so it's just 1 measure that day instead of 2? The incentives can be combined into one big bounty

**Comment by crlund2024** [comment]
@yago1994 Gotcha - should I just delete this issue once I've done that?

**Comment by yago1994** [comment]
@crlund2024 yes please!

**Comment by Wiza-Munthali** [comment]
Study Completed
