### ISSUE TITLE
Edit Notifications & tracking

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#365]
# Goal
Integrate notifications into Winship study to increase user submission of diaries. 

## Considerations
- Most of the notification patterns are the same as for the Validation study with a few date cutoff reminders
- A new notification_type should be scheduled: "dailygoal"
- Type of notifications should follow protocol below for categorization and tracking in Pendo
- Fire one Pendo track event for each notification that gets triggered
- Use status to track notification status: scheduled, cancelled, fired, opened (in order of description below)
- Remove the 'scheduled_by' variable since only "reminder" notifications are scheduled by the user
- Exchange the 'reminder_times' variable to 'scheduled_time' to avoid confusion with definitions
- Remove the 'number_of_reminders' variable and instead send one track event per notification scheduled
- Type of tracking events:
   1. Notification gets scheduled (ScheduleReminder, [status, notification_type, page, scheduled_time]) (to correlate this later in data analysis with app arrival)
   2. Notification gets cancelled (ScheduleReminder, [status, notification_type, page, scheduled_time]) (this will help determine how many notifications previously scheduled are cancelled, also will help knowing notifications removed manually in the Settings page if user receives too many notifications)
   3. [out-of-scope if big effort] Notification gets fired (if possible, remove the scheduled one) (ScheduleReminder, [status, notification_type, page, scheduled_time])
   4. [out-of-scope if big effort] User enters app through a notification ((ScheduleReminder, [status, notification_type, page, scheduled_time])
### For context
![Image](https://github.com/user-attachments/assets/2f6c2a52-2dc9-48c6-ba34-9cf64c894e5c)

### **Daily Reminder (scheduled by participants)**

🐰 All scheduled on the onboarding when the user sets the reminders.

🔫 Fired daily (M - F). Could be multiple notifications

⚠️ ALL Daily Notifications get removed if the user **starts a diary entry** → Reason for this is to avoid overburdening the user with general notifications if they start the entry on their own accord

⏲️  1x notification scheduled

- Title: "Record your interactions!"
- Content: "Hey there! Have you interacted with staff members today? Take a couple minutes to record your thoughts"

⏲️ ⏲️  > 1x notifications scheduled (These can vary if participants have > 2 reminders)

- Title: "Just a minute!"
- Content: "Hey there! Just another check-in. Don’t forget to record your thoughts after talking to the staff"

### **Late Afternoon Begin Reminder (scheduled by the system)**

🐰 Scheduled during the onboarding after setting the personal reminders

⚠️ Removed when the user **starts a diary entry**

🔫 Fired daily (M - F) unless the following conditions

- **IF NO** daily reminder (no time set by the user)
    - Fires random time between 1 - 3p (TBD the best time for firing)
- **IF YES** daily reminder (set by the user)
    - If ANY reminder is after 3p → schedule late night reminder +1hrs in the future (until 6:00p) → TBD need to define when not to bother users outside of their working hours (define working hours with PI)
    - If ALL reminders are before 3p → schedule late night reminder at 4:30p (end of work day)

⏲️ Notification

- Title: "Let's submit some entries!"
- Content: "Hey, it looks like you haven't made an entry yet. Don't worry; you can still submit an entry to record your interactions with staff! Click here to begin now."

### **(New) Goal Accomplishing Reminder (scheduled by the system)**

🐰 Scheduled dynamically on 1st daily submission

⚠️ Removed when the user **accomplishes the daily goal (3 entries submitted)** 

🔫 Fired daily (M - F) unless the following conditions

- **IF NO** daily reminder (no time set by the user)
    - Fires +2 hrs (TBD) after most recent submission (Date().now + 2hrs) until cutoff time of 6p
- **IF YES** daily reminder (set by the user)
    - If ANY reminder is after 3p → schedule +1hrs in the future (until 6:00p) → TBD need to define when not to bother users outside of their working hours (define working hours with PI)
    - If ALL reminders are before 3p → schedule at 4:30p (end of work day)

⏲️ Notification

- Title: "You are close to your daily goal!"
- Content: "Hey, you are just [one if 2 entries completed | two if 1 entry completed] conversation away from your daily goal. Keep it in mind as you wrap up your day and you talk to any staff along the way"

### **Continue Diary (scheduled by the system)**

🐰 Scheduled when the user **has begun a diary entry and the app is sent to the background (quits or phone closes) or when the user exits the flow**

⚠️ Removed when the user **completes the diary (arrives at the submission screen)**

🔫 Fired daily under the following conditions

- 1x Scheduled at Date() + 30 mins (until 23:59)
- 1x Scheduled at Date() + 6 hrs (until 23:59). If +30mins is scheduled, don’t schedule this one.

⏲️ +30 mins Notification

- Title: "Continue where you left off!"
- Content: "Looks like you started a diary entry but haven’t finished. Tap here to continue."

⏲️ +6 hrs Notification

- Title: "Continue where you left off!"
- Content: "Looks like you started a diary entry but haven’t finished. Tap here to continue, you only have a couple hours to finish it off before a new day begins!”

**Comment by yago1994** [comment]
@Wiza-Munthali Added the notifications protocol here, can you take a look for implementing in Winship?

**Comment by Wiza-Munthali** [comment]
Leaving the submit diary notifications in there to further validate the effectiveness of the notifications

**Comment by Wiza-Munthali** [comment]
>       2. Notification gets cancelled (ScheduleReminder, [status, notification_type, page, scheduled_time]) (this will help determine how many notifications previously scheduled are cancelled, also will help knowing notifications removed manually 

@yago1994 The notification package is not making it easy for me to retrieve the scheduled time for the notification so its not possible to pass in the `scheduled time` for this track event unless we pass in the notification id and we analyse with that

**Comment by yago1994** [comment]
@Wiza-Munthali is this merged into main? Not sure why the issue remained open.

We do have an issue on the user engagement test related to tracking in Pendo, if you have a second, can you go into Pendo and take a look at the visitor page and compare with Winship? The User Engagement test folks are getting very minimal tracking of their activity

**Comment by Wiza-Munthali** [comment]
@yago1994 how many users are expected/ or invitations were sent for user engagement?

**Comment by yago1994** [comment]
I think we covered this on the meeting last week but just for documentation it's 12 users
