### ISSUE TITLE
Incentives and Daily Goal and Weekly Goal

### ISSUE THREAD

**Issue by Naomi-Nyama** [AppHatchery/Fabla-Front-end#371]
@yago1994  and @crlund2024 

I wanted to ask for a clear description of the incentives and the Goals(daily and weekly) for the field test.

**Comment by crlund2024** [comment]
Daily goal is 2 EMA surveys and one diary for days 1-6 and 8-13
Weekly goal is at least 9 out of 12 completed EMAs, at least 4 out of 6 completed diaries

Full details [here](https://www.notion.so/apphatchery/User-Engagement-Fabla-Field-Test-Protocol-924d6d3d9acd455c93056adab0014e25) under Procedure and Incentive structure

- $50 for the entire study
    - “Regular” assignments mean not midpoint or final day stuff
    - Midpoint and Final days (MARS and diary completion) will each be worth $3
    - .50 cents for each “regular” EMA ($14)
    - $1 dollar for the 12 “regular” diaries ($12)
    - $10 for 70% completion rate (at least 9 completed regular EMAs and at least 4 completed regular diaries) in week 1
    - $10 for 70% completion rate (at least 9 completed regular EMAs and at least 4 completed regular diaries) in week 2

![field test incentive schedule](https://github.com/user-attachments/assets/25e75c1a-6ef1-408e-a374-434bfaeb1bb2)

**Comment by yago1994** [comment]
@crlund2024 can you add a diagram of the weekly schedule and the incentive available for each day to help Naomi understand? The notion link may create confusion

**Comment by yago1994** [comment]
@crlund2024 this adds up to $48 can you adjust the Day 7 and 14 to $3 to fix the match
