### ISSUE TITLE
Bug on onboarding question

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#387]
# Bugs
1. No data persistence (if the user goes back to the previous question, their previous answer is not saved)
2. Second onboarding question does not display correctly [Testing, might be related to Retool payload]
## Steps to reproduce
- Launch R10D experiment
- Answer the first onboarding question
- Go to the next question (null check operator error)
- Go back (earlier answer defaults back to 10)

## Retool Protocol
![Image](https://github.com/user-attachments/assets/77e67fa1-0fbf-4424-ac18-9567815e537a)

**Comment by Wiza-Munthali** [comment]
The options passed from retool is empty that's why the app is complaining

**Comment by Wiza-Munthali** [comment]
@yago1994  I replaced the question with the proper options and you can try it again

**Comment by yago1994** [comment]
Sounds good, did you look into data persistence?

**Comment by Wiza-Munthali** [comment]
> Sounds good, did you look into data persistence?

I'm currently working on it
