### ISSUE TITLE
Change title for Audio question options to 'Type my response'

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#389]
![Image](https://github.com/user-attachments/assets/87f2abc9-f9fb-4e65-a8ea-f062f676364e)

**Comment by Wiza-Munthali** [comment]
@yago1994 may you please explain the ticket, because the text option already has that title:

![image](https://github.com/user-attachments/assets/bc702b25-ebe4-4ad2-974a-8427e052094d)

**Comment by yago1994** [comment]
Oops, I think this came from feedback on a Figma screenshot 🙈
