### ISSUE TITLE
Crashlytics incompatibility with XCode 16

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#390]
# Error
Getting an error message from Crashlytics when updated to XCode 16 from Apple

**Comment by Wiza-Munthali** [comment]
## Steps to fix the error
1. Clean Cache
`flutter clean` or `flutter clean cache`

2. Remove pod and pubspec lock
`rm -rf pubspec.lock ios/Podfile.lock ios/Pods/`

3. Modify Pod file

- Change ios target
`platform :ios, '13.0'`
- Add the following line after the `config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']`
`config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES' `

4. Change xcode config

    open ios/Runner.xcodeproj with xcode
    click project -> Runner -> Build Settings
    in search bar: Allow Non-modular Includes in Framework Modules and changer Runner to yes.

5. Build
``` 
flutter pub get
cd ios/
pod install
```

6. Run
