### ISSUE TITLE
Notifications Redesign

### ISSUE THREAD

**Issue by Wiza-Munthali** [AppHatchery/Fabla-Front-end#391]
## Goal
Restructure how notifications are scheduled from the diaries. 

### Sub Goal
Add Pendo tracking from the Winship study

### Considerations
1. iOS only allows 64 notifications to be scheduled (Android is 500). Consider not going over this limit as notifications do not fire if crossed.

**Comment by Wiza-Munthali** [comment]
@yago1994 I am currently working on the notifications piece, trying to add the dummy notifications in the payload and i ran into an issue.

The current setup is the app gets the studies and diaries from the API then saves them in the local database, after that the app asks the user for notification access, then it takes all the diaries then creates the notifications for those diaries. So for the dynamic setup of notifications to work then we need to ask for notification access before we get the diaries (I'm trying to avoid keeping the notifications payload as we'll only use it once)

**Comment by yago1994** [comment]
@Wiza-Munthali got it, I made some re-arrangements to the onboarding in #394 can you check to see if it makes sense?
