### ISSUE TITLE
Awaiting Submissions

### ISSUE THREAD

**Issue by charlotteyao-emory** [AppHatchery/Fabla-Front-end#396]
One user complained that her submissions of the daily diary didn't go through and the App showed "Awaiting Submission" on the history tab when she checked. I also tried and when tapping on the "Awaiting Submission" Button, it didn't respond. It's supposed to reload and enable the user to submit the responses recorded.
![image](https://github.com/user-attachments/assets/5abedefd-395f-4f36-ab73-5711f52455c4)

**Comment by Wiza-Munthali** [comment]
@ yago1994 should we push an update to testflight fixing this problem or add the solution to M3 milestone?

**Comment by Wiza-Munthali** [comment]
@charlotteyao-emory Thanks for bringing this to my attention, I'll look at it
