### ISSUE TITLE
EMA & diary notifications are not working properly

### ISSUE THREAD

**Issue by charlotteyao-emory** [AppHatchery/Fabla-Front-end#400]
One user complained about the notifications for tasks: "For example, I am not getting notifications when a task Has started, unless I am already on the phone using it. I don’t have any way of demonstrating this to you because it’s the lack of something, not the presence. I am getting notifications when something is almost due, even though I have already done it."
I encountered this "receiving notifications for a diary that I've already finished"issue once during testing, too. But this issue only appeared once.

**Comment by yago1994** [comment]
Likely due to overload in scheduling notifications as seen in Pendo, likely this will be addressed by merging #399 . Will leave open for now.

**Comment by yago1994** [comment]
Confirmed that it's due to scheduling more than the iOS cap
