### ISSUE TITLE
Generate Pendo account based on Experiment

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#403]
# Goal
The Pendo account should be populated according to the Experiment Name (or perhaps Code?) and pulled as soon as the user has enrolled on the experiment.

Current implementation Pendo account is fixed for the app and the ID is dynamic, we should have the account be dynamic as well.

What do you think @Wiza-Munthali ID or Experiment name?

**Comment by Wiza-Munthali** [comment]
@yago1994 This sounds doable
