### ISSUE TITLE
Pendo Track Events for tracking users behavior

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#407]
# Goal
Add track event analytics to Flutter for tracking users behavior throughout the app.

Available here 
https://www.notion.so/apphatchery/Pendo-Analytics-Plan-10e02fae5b0680c595e8f8cf2c2f89e4

**Comment by Wiza-Munthali** [comment]
I have tackled most of the events, we'll need to go through them later to improve the collection of data
