### ISSUE TITLE
Add bonus to incentive page when user hits study milestone

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#408]
# Goal
Provide the user visual feedback of the incentive they have earned so far, specially for the bonuses that are applied according to study completion.

At a minimum the total incentive earned should reflect the bonus applied

**Comment by Wiza-Munthali** [comment]
This has already been implemented:
![image](https://github.com/user-attachments/assets/a6d9df8d-efcb-41e6-8a62-b82a287749f9)
