### ISSUE TITLE
[Retool] Bug on Question Type

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#412]
# Bug
When inputting the following message for the Subtitle of a question this error came up.

![Image](https://github.com/user-attachments/assets/6d059390-a21c-40a1-a43c-87499352813f)

These are the question parameters:
Title: Talk about your day today

Subtitle: Please try to talk without stopping for about **3-5 minutes**. Talk about whatever comes to your mind, as if you were sharing with a friend. Do not worry about pauses, stutters, or having the right things to say. We are interested in anything about your experience today that you are willing to share

## Expected behavior
We should be able to type in any content on the text cell for the question types.

See experiment CCSH

**Comment by kennedylinzie** [comment]
![image](https://github.com/user-attachments/assets/44dbd850-f38a-4d67-b5a8-00c092f735c4)

it was a content lenght limit for the subtype fixed
