### ISSUE TITLE
Bug in EMA creation, two EMAs got created when only one was specified in Retool

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#415]
[UPDATE] I could not reproduce this again so I'll deprioritize unless I can reproduce it again

See below
![Image](https://github.com/user-attachments/assets/dfef7c81-ad6e-49cc-b07d-5f8a1bf34c0b)
![Image](https://github.com/user-attachments/assets/e88fbfe6-e5e7-4708-9d9c-abad64a86f9b)

Experiment parameters:
CCSHT
P10

## Extra
- Also notification at 8:30 did not fire

**Comment by Wiza-Munthali** [comment]
You probably pulled from the API twice that's why there was a duplication

**Comment by yago1994** [comment]
Couldn't reproduce
