### ISSUE TITLE
Completed diaries not visible on the home page

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#416]
# Bug
The completed diaries are not visible on the home page

## Steps to reproduce
- Pulling from #411 
- Launch experiment CSSHT
- P10
- Change time to 8:30 AM
- Answer the diary
- Go back to the home page (diary will not be visible)

I believe we discussed this a few weeks back and we though it was related to the dummy payload, but this has the diaries coming from Retool
![Image](https://github.com/user-attachments/assets/b208b61d-2a06-4b20-a509-519dabfa2fb4)

There's also some strange behavior happening where the Home will go to an empty day state after submitting both Diaries due that day. Diaries are always visible in the History page.
![Image](https://github.com/user-attachments/assets/53113dc4-c68a-4494-bffc-1324b5259a99)

## Additional issues
- Weekly goal summary is correct but drop down appears empty, probably connected to #414

**Comment by Wiza-Munthali** [comment]
@yago1994 didn't we agree that completed diaries are only shown on the history?

**Comment by yago1994** [comment]
@Wiza-Munthali yes you are right, I think I was confused because the ghost would sometimes disappear, we can keep the finished diaries in the history page

**Comment by Wiza-Munthali** [comment]
@yago1994 can we get a design for when the user has completed all tasks? It doesn't look right it being empty or having the 'it's a free day' design showing up

**Comment by yago1994** [comment]
Agreed, @charlotteyao-emory can you take a look?

**Comment by charlotteyao-emory** [comment]
@Wiza-Munthali 
Here's a design for reference:
![image](https://github.com/user-attachments/assets/da3e554c-dc21-4cb9-acd5-0b3ba1a0a253)

and the icon of 🎉 used:
![image](https://github.com/user-attachments/assets/0667fc67-13cc-45aa-a328-1f614969219a)

**Comment by Wiza-Munthali** [comment]
@yago1994 @charlotteyao-emory, what if the person hasn't completed any of the entries but all the diaries are past due? Should we still display "Congratulations"?

**Comment by yago1994** [comment]
Excellent question, I'd actually propose to go with a more celebratory neutral image and text to avoid needing a custom state for congrats vs not congrats. Also how do we determine what deserves a congrats (1/5 entries completed?)

Because the ghost already reflects congratulations based on daily goal achievement, I'd propose to go with a neutral statement when nothing is left for the day

@charlotteyao-emory

**Comment by charlotteyao-emory** [comment]
@yago1994 @Wiza-Munthali let me know if this works:
![image](https://github.com/user-attachments/assets/9642b9cf-5212-4903-85ad-715a4e8ad4dd)

"Done"Icon used:
![image](https://github.com/user-attachments/assets/79a0babf-88fa-4c4a-bbe4-5cfc0a351eac)
