### ISSUE TITLE
Pendo Guides for Content Creation

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#432]
# Goal
Offload creation of pop-ups from Flutter to Pendo

## Tasks
1. Finish Creating Study Details pop-up, template already available in Pendo under CCSH - Study Details
  - You can test it by clicking Test on the Design Manager window in Pendo and click on the Study Details button on the app (you'll need to delete the previous app and install fresh to bring the latest dependencies for Pendo).
  - ![Image](https://github.com/user-attachments/assets/978319fb-7139-4d19-aa0c-4961a8459b70)

2. Create Home page pop-up, for reference here is the Figma
![Image](https://github.com/user-attachments/assets/b80d57f0-973a-47d2-bcea-70f2e1620ec7)

3. Create the Diary pop-up
![Image](https://github.com/user-attachments/assets/9b6018aa-18f2-43a7-8cc8-8b3473aa978a)

## Considerations
- You can create styles in Pendo, that way we can select them to maintain a consistent style of color, font, etc,. across all guides
- For testing the guides we can connect them to the Track Events (HomePopUp and DiaryPopUp) and navigate to those pages
- Make sure you are running #424 PR to bring in the latest Pendo functionality

**Comment by yago1994** [comment]
@charlotteyao-emory I took a quick look at Pendo and I see the guides, they look very high fidelity! 

Make sure that you also review the one for the Study Details, for this we will want to include the content from the consent form. I've clipped some of it below and you can edit it further.

"Emory Spiritual Health has developed a Compassion-Centered Spiritual Health group-based intervention, called CCSH Interventions for Teams, and are enrolling staff and providers into the groups in a randomized, step-wedge design. The groups meet once every other week for 60 minutes for 8 weeks (4 sessions total). The purpose of this voluntary study is to evaluate the feasibility and acceptability of CCSH Interventions for Teams and to understand how to optimally implement CCSH-TI. You are being asked to volunteer because you are a full-time employee at Winship Cancer Institute or at Emory St. Joseph who will be enrolled in one of the CCSH Interventions for Teams at some point during the next 16 months. You will be asked to complete a set of questionnaires at 3 different time points before and after the CCSH intervention over the course of approximately 22 weeks. We estimate that approximately 80 participants will participate in this study.

What will you be asked to do?
This study will take place at the Winship Cancer Institute or at St. Joseph and will involve the following:
1. You will be asked to complete a set of online questionnaires at three timepoints over the course of the study. The online questionnaires will be distributed to you by email and accessed using a link to a Qualtrics survey.
2. You will be asked to complete a 3-day ambulatory assessment that will include ecological momentary assessment (EMA) and electronically activated recorder (EAR) to measure perceived and objective factors relevant to testing the effectiveness and mechanisms of action of CCSH-TI.
3. Participants will also be offered a chance to participate in a 30-60-minute focus group after completing CCSH-TI.

Contact Dr. Jennifer Mascaro at 404-558-4461
- if you have any questions about this study or your part in it,
- if you feel you have had a research-related injury
- if you have questions, concerns or complaints about the research"

**Comment by charlotteyao-emory** [comment]
@yago1994  i have edited the study details page but now I have a dumb question: what will be the duration of study displayed here

<img width="306" alt="image" src="https://github.com/user-attachments/assets/a354469a-29c6-4688-a81c-0cbbcfe503b0">

Is it 8 weeks or 22 weeks? or 30 weeks?

**Comment by yago1994** [comment]
Moving text conversation here, let's do 6 months

**Comment by yago1994** [comment]
Completed in Pendo
