### ISSUE TITLE
Add Linker Flag to project

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#44]
"-lc++"

**Comment by Wiza-Munthali** [comment]
@yago1994 can you guide me where to add the flag, I can't find the "other flag" row in the linking column

<img width="1680" alt="image" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/42870528/d11b3cd4-2a7f-4428-a634-d3ee534e0809">

**Comment by yago1994** [comment]
@Wiza-Munthali tough to find, best is to use the Search on the top right corner for "Linker"
![image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/03a705bd-b64b-4f74-9df1-c6c17bf0ca43)

Double click the string and 
![image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/c4dca305-1153-4093-9ce0-f7a60d0e3404)

**Comment by Wiza-Munthali** [comment]
Nope, nothing there

<img width="1680" alt="image" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/42870528/da143130-567d-4de1-bba3-7a0855bef4a5">
