### ISSUE TITLE
Closed diaries display "ready to start"

### ISSUE THREAD

**Issue by MorganGreenleaf-Emory** [AppHatchery/Fabla-Front-end#453]
![image](https://github.com/user-attachments/assets/559e37cf-206b-4080-a1d9-3c39e3251698)

**Comment by Wiza-Munthali** [comment]
This was covered in #442 

Picture taken from main
![Image](https://github.com/user-attachments/assets/be2c19be-8a72-4019-ad5e-0c0758da75ca)
