### ISSUE TITLE
iOS - selecting push reminder for diary takes user to correct page, but diary isn't open

### ISSUE THREAD

**Issue by MorganGreenleaf-Emory** [AppHatchery/Fabla-Front-end#454]
Refreshing page by switching tabs resolves issue

![image](https://github.com/user-attachments/assets/9dcbdf63-f0d6-44c7-998c-e2150e75fc9c)

**Comment by Wiza-Munthali** [comment]
Already been fixed:



https://github.com/user-attachments/assets/9edfd062-e1bf-4aa5-bcc6-088cbd3270b5
