### ISSUE TITLE
Bug on reorganizing questions

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#462]
# Bug
Questions don't appear in the order specified in Retool when they are moved with the arrows.

## Steps to reproduce
- Open PTEST experiment and go to Questions for Survey 3
- Question ID 273 should appear first but shows up last in Flutter

**Comment by kennedylinzie** [comment]
@hopemadziakapita

**Comment by hopemadziakapita** [comment]
Solved in RDSNodeAPI [PR 117](https://github.com/AppHatchery/FablaRdsNodeApi/pull/117)
