### ISSUE TITLE
Add UI of non-audio questions to diaries

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#49]
# Secondary Goal
Add non-audio questions to summary page

## Considerations
- Let's be consistent and display a review page without editing abilities
- Sliders don't need to have the number displayed
<img width="325" alt="image" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/73d2b397-7231-472b-b588-c204dbad12d3">
<img width="322" alt="image" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/d8f72825-ece6-433e-a511-7399b227621a">

##

# Goal
These questions will appear in this order BEFORE the audio diary response questions.

Total Diary flow
- Questions 1 - 11
- Diary Questions 12 - 13

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/53ea0e6d-18cb-4fbd-a84f-bc398195f78f)

## Considerations
- No pop-up for data saving is necessary, when the user clicks continue they move forward
- 'Continue' button should be disabled until the user makes a selection on screen
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/455b47fc-f5a8-46c8-ad24-f7957fab2e9b)

## Out of Scope
- Ignore Data saving and submission for the time being

## Discrete Slider
- Only whole units (1, 4, 7) are allowed (i.e. NOT 3.5)
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/eb2163e0-edf4-4165-bfdb-bf65dbd05e24)

## Multiple Choice
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/8cb89a33-4ec9-4ba8-af67-5d1983183942)

![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/21e51bd8-b5ee-4c82-b39f-8d9b023b99ec)

## [DEPRECATED] Entry
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/b7dcf131-5aed-4c49-a98a-171f99eaa2e4)

⚠️ Alcohol question has been changed to a slider
0 -> 12 or more

**Comment by yago1994** [comment]
@yago1994 to check-in with researchers about data formatting and requirements

**Comment by yago1994** [comment]
@Naomi-Nyama checking in with the researchers we are changing the last response (free input) to a slider as well to simplify development and data collection. I've updated the ticket to reflect that, hopefully you didn't get started on it

**Comment by yago1994** [comment]
@JayceKongg from meeting today, how does the summary page change with extra questions?

**Comment by JayceKongg** [comment]
See the Figma mockups of the summary page here. We can remove the editing feature (for now) from the summary page to make it more simple. I included it in the design.

<img width="1245" alt="Screenshot 2023-09-22 at 00 53 29" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/d5205315-49f1-43d8-ad12-ee23ffcaae1e">

<img width="1245" alt="Screenshot 2023-09-22 at 00 55 50" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/3112d322-4535-418d-9281-22cc9b222a8d">

https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4523%3A36154&mode=design&t=xQ5TSdZG84wLUNeC-1

**Comment by yago1994** [comment]
@JayceKongg thanks for the screens. We'll go with the no-editing version of this because allowing editing is too complex at this stage. One note, the number displayed on the selection of the slider may not be possible since may not be supported by the package.

**Comment by JayceKongg** [comment]
Update:
1. Change the color of options on the survey page (empty and active state);
2. Remove confirmation for non-audio response;
3. Remove header "New Daily Diary" of the survey page;
4. Add a progress indicator;
5. Add the question number (i.e., question 1 /13) above the question title;
6. Add a "back to previous question" button on the left of the "continue" button;
7. Replace the "I don’t want answer this question" by a "Skip" at the top right.

<img width="650" alt="Screenshot 2023-09-24 at 00 48 35" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/ae4ef437-5c7e-4846-8dde-13d66c35793d">
<img width="650" alt="Screenshot 2023-09-24 at 00 48 53" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/0f6cb3f0-7f34-4442-bc5a-ed9971ccac0c">
<img width="650" alt="Screenshot 2023-09-24 at 00 49 05" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/68ba35eb-ab77-4dcc-9dad-4178e57bed78">


Figma Link:
https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4578%3A45174&mode=design&t=prgklExUWmOlgwWq-1

**Comment by yago1994** [comment]
@Naomi-Nyama can you take a look at the back button? I want to hear your take on whether it's feasible and would be simpler than having the native navigation stack (particularly iOS)

I'm going to wrap 
- Remove header "New Daily Diary" of the survey page;
- Add a progress indicator;
- Add the question number (i.e., question 1 /13) above the question title;

To a polish issue #79

**Comment by Naomi-Nyama** [comment]
@yago1994 This would maybe be okay for now, but wouldn't it be simpler to just alter the behaviour of the (x) Icon button?
- so that when its on the first page(first question in the PageView) its x and it takes you back to the home page or diary tab but when the participant moves to the next question page in the pageView it should change to <- that navigate back button and take the user to the previous page in the pageView. the skip page could just close the entire diary and go back to home page

**Comment by yago1994** [comment]
@Naomi-Nyama following on our converstaion this morning.

Covering the navigation issue in #80 . You close this ticket when you are ready.
