### ISSUE TITLE
Change app name and add app icon

### ISSUE THREAD

**Issue by Wiza-Munthali** [AppHatchery/Fabla-Front-end#5]
# Goal
Determine the app name and design logo

## App Name: Fabla

Logo
![White](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/e74cb0c6-ac3f-4ed0-9e2d-f70389642c3a)

### Goal

- Change app name from AudioDiariesFlutter to Dayrio
- Change the stock app icon to the intended app icon

**Comment by Wiza-Munthali** [comment]
@JayceKongg do we have a launcher icon for the application?

**Comment by JayceKongg** [comment]
> @JayceKongg do we have a launcher icon for the application?

We don't have it for now, will do it.

**Comment by yago1994** [comment]
> > @JayceKongg do we have a launcher icon for the application?
> 
> We don't have it for now, will do it.

We should get a name first and then build a logo after that. We can involve a few folks for a small brainstorm, happy to run this in the next two weeks

**Comment by yago1994** [comment]
Also covered in #117
