### ISSUE TITLE
Flip back and forth logic

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#50]
# Goal
The diaries presented to the user should switch in this manner

## Considerations
- This issue has a dependency for a study start date variable generated in #53 

## Prompts for Days 1, 3, 5
**Talk about your day today.** 

Please try to talk without stopping for about 5 minutes. Talk about whatever comes to your mind, as if you were sharing with a friend. Do not worry about pauses, stutters, or having the right things to say. We are interested in anything about your experience today that you are willing to share.

**Talk about a time today when you felt understood or cared for by others, no matter how small.** 

Please try to talk without stopping for about 5 minutes. Talk about whatever comes to your mind, as if you were sharing with a friend. Do not worry about pauses, stutters, or having the right things to say. We are interested in anything about your experience today that you are willing to share.

(It is OK if there is overlap with what you talked about for the previous question.)

## Prompts for Days 2, 4, 6
**Talk about your day today.** 

Please try to talk without stopping for **about** **5 minutes.** Talk about whatever comes to your mind, as if you were sharing with a friend. Do not worry about pauses, stutters, or having the right things to say. We are interested in anything about your experience today that you are willing to share.

**Talk about today’s most stressful experience, no matter how small.** 

Please try to talk without stopping for **about 5 minutes.** Talk about whatever comes to your mind, as if you were sharing with a friend. Do not worry about pauses, stutters, or having the right things to say. We are interested in anything about your experience today that you are willing to share.

(It is OK if there is overlap with what you talked about for the previous question.)

## Considerations
- The prompt title will be the header
- The prompt description will be the Researcher's Note

**Comment by yago1994** [comment]
@Wiza-Munthali  Make sure the Considerations section is accounted for, part of it is more UI logic which can be bundled in a different ticket. If you want to push it out of this issue just make a new ticket and add it in.

**Comment by Wiza-Munthali** [comment]
@yago1994 Both considerations have been accounted for.
