### ISSUE TITLE
SubjectID list

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#54]
# Goal
Determine the mapping between the subject IDs and the branch of the study they will be on

## ✅ Need to know
- Length of file
- Distribution of Branch allocation (even numbers app first, odd numbers survey first)
- Format of list for easy reading
- ALL participants will start the study on Nov 6th

[Voice Diary Participant Tracking.xlsx](https://github.com/AppHatchery/Audio-Diaries-Flutter/files/12819441/Voice.Diary.Participant.Tracking.xlsx)

**Comment by Wiza-Munthali** [comment]
@yago1994 there's a contradiction of start dates between this ticket and #116 , may you clarify please.

**Comment by yago1994** [comment]
> @yago1994 there's a contradiction of start dates between this ticket and #116 , may you clarify please.

Nov 6th it is! Thanks for asking for clarification

**Comment by Wiza-Munthali** [comment]
@yago1994 So the survey people will start the study on the 12th?

**Comment by yago1994** [comment]
> @yago1994 So the survey people will start the study on the 12th?

By starting the study if you mean start the APP study, then yes, they all will start the OVERALL study on the 6th
