### ISSUE TITLE
Pendo

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#56]
# Goal
Incorporate Pendo to the project

## Considerations
- Integrate Pendo into the project (iOS/Android are under the AppHatchery Pendo account)
- Verify connectedness for both platforms
- Make sure Pendo is initialized both from the onboarding and from the main screen

## Instantiate
- Pendo should be instantiated after the user has input their subject ID
- VisitorId = subjectId
- AccountId = "Validation-Study-Fall23"

For Testing Use
- AccountId = "Test-Fall23"

## Open questions
- How can we use a release branch with Pendo setup so that development work doesn't push data to the study account?

**Comment by Wiza-Munthali** [comment]
I'll take this one cause I have Xcode
