### ISSUE TITLE
Polish Diary Tab

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#59]
# Goal
Polish the Diary Tab

## Tasks
- Date of submission should be **the date the diary was DUE** (not the date it was actually submitted, this is particularly relevant for the 4am cutoff, we don't want to confused participants having multiple diaries under the same date)
- Calendar view is not responsive, just highlights the current date
   - Expected behavior is to display the diary that occurred that day
- Only today's diary should be "Startable" the past ones can only be viewed

**Comment by Wiza-Munthali** [comment]
@yago1994 Question: Are the users allowed to look at upcoming diaries? For example if today is the 1st and I have diaries starting on the 5th can I use the calendar to go that specific date and see the diary??

**Comment by yago1994** [comment]
Good question, they are not allowed to view the diary, but they are allowed to know there is a diary on that day. There’s a bit of a disparity on the Diaries page when the calendar is not interactive. However if it is it creates a question about what to do with the diary days. Jayce is working on a state for cards that are not allowed to be viewed yet which id like to talk about Monday and see how feasible it is

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yago1994** [comment]
Closing this issue because it's been worked as part of other tasks
