### ISSUE TITLE
Upload multiple choice data to DataStore

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#65]
# Goal
To enable the easiest data collation for the researchers, all the data from all participants should be within the same structure. That way it can be downloaded as a single file to be analyzed. 

Similarly to Firebase Realtime database, AWS has a service that allows data to be stored in a JSON format. 
https://docs.aws.amazon.com/whitepapers/latest/amplify-datastore-implementation/amplify-datastore-overview.html

## Considerations
- Each participant should upload their multiple choice data under their identifier parent, i.e. P1001
- The structure of the data inside the parent node for the participant IDs should be FLAT (No Nesting), this will enable the data to be easily converted to a csv file such as this below
![Image](https://user-images.githubusercontent.com/16402216/268322091-c6698a33-2ca0-4085-9b60-c58812a18a83.png)
- Each participant submission should update the parent node by editing new fields (i.e. if there is data already for  P1001 PHYSICALLY_1 : 3, which corresponds to the first submission to the study; the update of the parent for the second submission of the study should be PHYSICALLY_2: 3)
- Every participant needs to have entries for every field of the study in order for the data to be organized effectively

## Data Format under parent node
- ParticipantID
- Start_time_x (x represents the day of the study 1 - 6). Start_time is the datetime the diary begins
- End_time_x. Start_time is the datetime the diary begins

## Tasks
1.  Set up the DataStore service
2. Upload some dummy data
3. Download the data and convert to a .csv 
4. Update data in the parent node (without deleting/overwriting old data!)

**Comment by yago1994** [comment]
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/8dbe8e43-a55e-4c0c-a54e-4991ac7082f1)

**Comment by Ikay-real** [comment]
@yago1994 Update works

**Comment by yago1994** [comment]
Wonderful @Ikay-real really nicely done.

## Notes
- All variables will have _# at the end (# representing the number of the day of the study)
- Every submission should include:
  - ParticipantID
  - Start_time_x (x represents the day of the study 1 - 6). Start_time is the datetime the diary begins
  - End_time_x. Start_time is the datetime the diary begins
- Slider question variables should be Int
- Multiple choice questions (9 & 10) should be String
- Empty fields should be filled with "."


## Variables
PHYSICALLY
EMOTIONALLY
INTENSITY
LONELY
LEFT_OUT
SOCIAL_INTERACTION
UNDERSTOOD
STRESSED
WHERE_YOU_ARE
PEOPLE_AROUND_YOU
DRINKS

**Comment by Ikay-real** [comment]
@yago1994 Thinking about the Start_time_x  and End_time_x., have you thought how we are supposed to represent them in the csv style table?
