### ISSUE TITLE
Notifications Scheduling

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#81]
# Goal
Schedule notifications

## Considerations
- Refer to https://www.notion.so/apphatchery/Notifications-a286edf59ac942599e016ce907dd748a
- No need for trackers on this ticket, that will be included in #87 

## Notifications included
- Day Prior Notification (scheduled by the system)
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/67717df1-ae4d-4214-94f5-3ddc9cfc38a9)
- Daily Notification(s) (scheduled by participants)
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/d6ce5de7-71b0-4810-b571-3a7f52ce1908)
- Late Night Reminder (scheduled by the system)
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/3c4c6618-01bf-42b0-99ee-c339bcf7b02b)

## These two below are a lot more custom and tricky (in my opinion). So let's divide the scope between the top ones and the bottoms ones. 
- Continue Diary (scheduled by the system)
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/a88ef440-978b-43fe-9f1a-2bf1ca5eb293)
- Submit Diary (scheduled by the system, NOT recurring)
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/ee0f8303-fe23-41af-8fb5-009b717c4f32)

## 

# Previous Goal
Design Notifications Schedule for:
- Continue Diary
- Submit Diary
- Don't forget Diary

TBD
- Dynamic content for your forgot last diary, don't forget this one

**Comment by JayceKongg** [comment]
**Continue Diary:** 
Title: "Keep Going on Your Diary Journey!"
Content: "Hey there! You're doing great, but it's time to continue your diary. Your insights matter!"

**Submit Diary:** 
Title: "Your Diary Is Ready for Submission!”
Content: "You've completed your diary. Fantastic! Just one more step: hit 'Submit' to share your valuable thoughts.”

**Don't forget Diary:** 
Title: "Friendly Reminder: Diary Time!”
Content: "Don't forget to start your diary or continue where you left off. We appreciate your input!”

**Dynamic content for you forgot last diary, don't forget this one**: 
Title: "Remember Your Last Diary Entry?"
Content: "You missed your last entry, but no worries! Let's make this one count. Share your experiences with us."

**Comment by yago1994** [comment]
@Wiza-Munthali I'm guessing you may take care of this issue, it's pretty big lift so let me know if you need me to chime in or help define the states better to make it easier to integrate. For testing protocol I'm thinking:

## Tips
What I would do is set a global variable that defines the time when you want the notification to fire, and every time you are testing a notification move that variable 1 or 2 mins in the future, or use Date() + 2 mins. That way you can cycle through notifications without having to change each individually.

Also I would print every notification scheduled and the scheduled date (i think you are already doing that) and it will be a second confirmation that it's scheduled to be sent

## Steps (a suggestion)
1. Make sure notifications are firing (duh). Schedule 5 second notification when user starts the diary.
2. Test one notification at a time
  1. Day before notification: Program notification in a couple minutes. Go through onboarding. Pick user 1001. Move datetime to day before diary starts. (easy)

  2. Day of notification: Program notifications manually on the onboarding to be in the next couple of minutes. Plan the next notification to be 2 mins after the first one. Do it through the UI. Go through onboarding. Set the diary to start today (ID 0000). Notifications should fire. 
      1. Part 2: follow same procedure and then start the diary. Notification should not fire. 


  3. Late night reminder. These are a bit more tricky. 
     1. Part I: Go through onboarding. Don't schedule reminders. Change datetime to 8:59p. Receive notification.
     2. Part II: Go through onboarding. Don't schedule reminders. Start Diary. Don't receive notification.
     3. Part III: Go through onboarding. Schedule a reminder at 11a. Change datetime to 8:59p. Receive notification. 
     4. Part IV: Go through onboarding. Schedule a reminder at 7p. Change datetime to 9:59p. Receive notification. 
     5. Part V: Go through onboarding. Schedule a reminder at 11p. Change datetime to 11:58p. Receive notification.
