### ISSUE TITLE
Diary Questions UI Polish

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#88]
# Goal
Polish items for the Diary Question pages

## Tasks
- Remove the edit button from the recording modal since it's not being use
- Adjust spacing
- Adjust timer
- Changes in Recording Modal
  - Remove Audio Tab
  - Add the close button
  - Add the Scroll indicator
- Adjust padding of the progress bar to the margins to 16px (same as content below)
- Next Question does not have the back button (aka the user can't go back)
- Dismiss the researchers note when the user presses save on the recording (this is to reduce the amount of clutter in the page)
- [Question] If a user exits the app before finishing the diary, can we bring them back to the previous question they were on if they press the 'Continue' button on the home page? Currently it brings them back to the first question

## For reference
Spacing
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/6c580a3e-3c7d-43a2-93a0-f8d6e69ad579)
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/8a234619-6a37-477b-94ab-08f8610d1cb7)
![Image](https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/16402216/649b20ad-bd52-4933-a279-768615bf4786)

@JayceKongg can you add here the image with the updated layout?

**Comment by JayceKongg** [comment]
Update:
- UI polish (Remove the edit button, Adjust spacing, Adjust timer, Remove Audio Tab)
- Add alternatives (speech bubbles and mascot facial expressions) for states 'BeforeStart,' 'Ongoing,' and 'Pause.'
- @yago1994 Do we have time to update the mascot's static facial expressions? I will have them ready by Tuesday morning.

<img width="1000" alt="Screenshot 2023-10-02 at 10 32 08" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/371a1e9b-e1f3-40f7-b54b-b086f660a066">

https://www.figma.com/file/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?type=design&node-id=4846%3A26783&mode=design&t=PykDxrbdYpQrXpwJ-1

**Comment by yago1994** [comment]
These are cool @JayceKongg , I think we can but have to fit it in the backlog. My question is, how are the transitions? As in, from one state to the next

**Comment by JayceKongg** [comment]
> These are cool @JayceKongg , I think we can but have to fit it in the backlog. My question is, how are the transitions? As in, from one state to the next

Good question, I think we need simple transition animations. Let me look into it first. Update later.

**Comment by JayceKongg** [comment]
Update:

**Transaction between different states (Before, Ongoing, Pause)**
- Mascot animation: Lottie loop animation (will update later)
- Speech bubbles: Add in-betweening animation between different-sized bubbles. Fortunately, the size of bubbles of 'before', 'ongoing', and 'pause' is different, so we can do in-betweening animations.

Animation video:
https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/cb5a47ea-85ad-4134-86b5-f8646357e6c7

Figma prototype Link:
[https://www.figma.com/proto/cZNaT1L5AbSk9bdIsry74i/Audio-Diaries-Design---Participant-Side?page-id=4855%3A24327&type=design&node-id=4855-24356&viewport=710%2C651%2C0.43&t=TX9ExXMjU0gVDl5Z-1&scaling=min-zoom&starting-point-node-id=4855%3A24356&mode=design](url)

**Comment by JayceKongg** [comment]
Lottie Link: (They are slightly different from Figma animation prototypes as Lottie does not support vectors in Figma plugin)

https://app.lottiefiles.com/share/360c40a7-e625-4047-884c-cabbece67b5b
https://app.lottiefiles.com/share/57c9a7a6-d67f-464f-a2f5-bbadc00a33e2
https://app.lottiefiles.com/share/0fdb4113-4b5b-4fb4-ad89-da349df5f2cb

Lottie JSON:
[LottieJSON.zip](https://github.com/AppHatchery/Audio-Diaries-Flutter/files/12787260/LottieJSON.zip)

I just added basic animations since we plan to replace the mascot. I thought it would be nice to try LottieFiles to see if it works for development. (I don't think it would be too hard, I use Lotties a lot in Webflow). Here are articles on how to add Lottie animations to your IOS and Android apps.

IOS: [https://lottiefiles.com/blog/working-with-lottie/how-to-add-lottie-animation-ios-app-swift](url)

Android: [https://lottiefiles.com/blog/working-with-lottie/how-to-add-lottie-animation-ios-app-swift](url)

**Comment by JayceKongg** [comment]
Update: Add a 'close' button to the top right of the recording model.

<img width="689" alt="Screenshot 2023-10-03 at 21 04 47" src="https://github.com/AppHatchery/Audio-Diaries-Flutter/assets/134336047/ce868192-f82a-4b36-b24b-5026fc84bdee">

**Comment by yago1994** [comment]
@Wiza-Munthali heads up in case you already started on this. I edited the ticket and added a couple extra tasks, let me know if you have any questions. Specifically:
- Add a close button
- Add scroll indicator
- Next question button in the banner does not have a back button
- Dismiss the researchers note when the user taps on 'Save' the recording
