### ISSUE TITLE
Test Protocol

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#93]
# Goal
Carry out pilot testing within the team to identify: Bugs, Crashes, Performance issues, Usability Issues, and overall experience of being part of the study.

## Testing Protocol
- Have all open and pending PRs merged on Friday. Specifically:
   - Notifications PR
   - DataStore PR
- Everybody install the app from main
- Select an identifier provided by @Wiza-Munthali (you may be assigned to Sunday or the following Saturday). Wiza I suggest we do 5 (Sunday) & 2 (Saturday next week) to emphasize testing as soon as possible and leave 2x people to make sure that the Saturday works.
- Try to answer the diaries at different time points:
   - Early morning
   - Afternoon
   - Night
   - (Past Midnight, if you are a night owl)

## Considerations
- Please write down on a ticket or notion the issues you identify as you see them
- Install the app on your phone and if you have work on testing something, make a separate testing bundle to not interfere with the 'testing run'
- This is our chance to take off our developer hats and try to behave like a user, it's also an empathy building exercise so enjoy stepping into a different persons shoes 👞

**Comment by Wiza-Munthali** [comment]
So not to end up choosing the same study code and having overriding issues, I am going to assign the subject codes.

### Group 1
@kennedylinzie : 1003
@Ikay-real : 1000
@Naomi-Nyama : 1006
@MorganGreenleaf-Emory : 1001
@JayceKongg : 1005

### Group 2
@Wiza-Munthali : 2005
@yago1994 : 2009
@MorganGreenleaf-Emory - iOS: 2001


## ⚠️ INSTALL THE APPLICATION ON RELEASE MODE (This is will allow the app to run at full capacity)

**Comment by yago1994** [comment]
Closing as part of the M1 cycle for the Validation Study
